// app/players/data.ts
export type OrgCode = "JPML" | "NPM" | "最高位戦" | "RMU" | "μ";

export const MLEAGUE_TEAMS = [
  "BEAST X",
  "EX風林火山",
  "TEAM RAIDEN / 雷電",
  "KONAMI麻雀格闘倶楽部",
  "セガサミーフェニックス",
  "赤坂ドリブンズ",
  "U-NEXT Pirates",
  "渋谷ABEMAS",
  "EARTH JETS",
  "KADOKAWAサクラナイツ",
] as const;

export type MLeagueTeam = typeof MLEAGUE_TEAMS[number];
export type Gender = "male" | "female";

export interface AllPlayer {
  id: string;
  name: string;
  nameEn: string;
  org: OrgCode;
  title: string;
  tags: string[];
  league: string;
  period: string;
  joinYear: number;
  birthday: string;
  gender: Gender;
  href: string;
  mleagueTeam?: string;
  birthplace?: string;
  bloodType?: string;
  hobby?: string;
  nickname?: string;
  titles?: { year: string; name: string; sub?: string }[];
  bio?: string[];
}

export const ORG_META: Record<OrgCode, { color: string; label: string }> = {
  JPML:    { color: "#c8282a", label: "日本プロ麻雀連盟" },
  NPM:     { color: "#2563eb", label: "日本プロ麻雀協会" },
  最高位戦: { color: "#7c3aed", label: "最高位戦" },
  RMU:     { color: "#a07e28", label: "RMU" },
  μ:       { color: "#2f5c3f", label: "麻将連合μ" },
};

export const ALL_PLAYERS: AllPlayer[] = [
  // ── TEAM RAIDEN / 雷電 ───────────────────────────────────────
  { id: "setokuma",    name: "瀬戸熊直樹",  nameEn: "Naoki Setokuma",      org: "JPML",  title: "鳳凰位×3",      tags: ["攻撃型","A1"],    league: "A1",    period: "第14期", joinYear: 1997, birthday: "1970/08/27", gender: "male",   href: "/players/setokuma",    mleagueTeam: "TEAM RAIDEN / 雷電", birthplace: "千葉県", bloodType: "O型", hobby: "海外ドラマ・漫画・アニメ", nickname: "暴君", titles: [{year:"2013",name:"第30期十段位"},{year:"2012",name:"第29期鳳凰位"},{year:"2012",name:"第29期十段位"},{year:"2011",name:"第28期十段位"},{year:"2010",name:"第27期鳳凰位"},{year:"2009",name:"第26期鳳凰位"}] },
  { id: "hagiwara",   name: "萩原聖人",    nameEn: "Masato Hagiwara",     org: "JPML",  title: "A1リーグ",       tags: ["俳優","A1"],      league: "A1",    period: "第17期", joinYear: 2001, birthday: "1971/08/21", gender: "male",   href: "/players/hagiwara",    mleagueTeam: "TEAM RAIDEN / 雷電", birthplace: "神奈川県茅ヶ崎市", bloodType: "B型", hobby: "映画鑑賞", nickname: "俳優雀士", bio: ["「俳優雀士」萩原聖人。神奈川県茅ヶ崎市出身、1971年生まれ。俳優・声優・ナレーターとして第一線で活躍しながら、麻雀番組にも90年代から出演し続けた唯一無二の存在。","2018年、日本プロ麻雀連盟に第17期生として入会（47歳でのプロデビュー）。同年よりMリーグ・TEAM RAIDEN/雷電のメンバーとして参加。攻撃的で高打点を目指す「魅せる麻雀」が持ち味。","趣味は映画鑑賞。俳優としての表現力を麻雀にも活かし、対局中の佇まいや仕草にもファンが多い。"] },
  { id: "kurosawa",   name: "黒沢咲",     nameEn: "Saki Kurosawa",       org: "JPML",  title: "女流桜花×2",     tags: ["女流","A1"],      league: "A1",    period: "第22期", joinYear: 2006, birthday: "10/06",     gender: "female", href: "/players/kurosawa",    mleagueTeam: "TEAM RAIDEN / 雷電", birthplace: "北海道札幌市", bloodType: "A型", hobby: "料理・お酒", nickname: "鉄壁の女王", bio: ["「強気のヴィーナス」黒沢咲。北海道札幌市生まれ、東京都世田谷区出身。生年は非公開（10月6日生まれ）。上智大学理工学部化学科卒業という高学歴の持ち主。","日本プロ麻雀連盟A1リーグに所属し、女流ながら男性プロと同じリーグで戦う実力者。副露率わずか8%という圧倒的なメンゼン思考で高打点を追求するスタイルが特徴。Mリーグには2018年発足時からTEAM RAIDEN/雷電のメンバー。","趣味は料理とお酒。「鉄壁の女王」の異名どおり、守りの固い麻雀と攻撃的な打点のバランスが絶妙。"] },
  { id: "honda",      name: "本田朋広",    nameEn: "Tomohiro Honda",      org: "JPML",  title: "鳳凰位",        tags: ["A1"],            league: "A1",    period: "第22期", joinYear: 2006, birthday: "1983/10/03", gender: "male",   href: "/players/honda",       mleagueTeam: "TEAM RAIDEN / 雷電", birthplace: "富山県高岡市", bloodType: "A型", hobby: "格闘技観戦・筋トレ", nickname: "北陸の役満プリンス", bio: ["「北陸の役満プリンス」本田朋広。富山県高岡市出身、1983年生まれ。金沢星稜大学卒業後、25歳で地元富山県砺波市に雀荘「麻雀サークルSB」を開業。2006年に日本プロ麻雀連盟第22期生としてプロ入り。","役満和了を複数回達成していることからその異名がついた。2021年よりTEAM RAIDEN/雷電のメンバーとしてMリーグに参加。現在も富山で雀荘経営と東京でのMリーグ活動を両立している。","趣味は格闘技観戦と筋トレ。血液型A型、身長180cm。北陸を代表するプロ雀士として地元への貢献にも力を入れている。"] },

  // ── KONAMI麻雀格闘倶楽部 ────────────────────────────────────
  { id: "sasaki",     name: "佐々木寿人",  nameEn: "Toshihito Sasaki",    org: "JPML",  title: "十段位",        tags: ["攻撃型","A1"],    league: "A1",    period: "第19期", joinYear: 2003, birthday: "1979/08/01", gender: "male",   href: "/players/sasaki",      mleagueTeam: "KONAMI麻雀格闘倶楽部", birthplace: "宮城県仙台市", bloodType: "O型", hobby: "桃鉄", nickname: "卓上の暴君", titles: [{year:"2023-24",name:"第45期十段位"},{year:"2022-23",name:"第44期十段位"},{year:"2020-21",name:"第37期十段位"},{year:"2019-20",name:"第36期十段位"},{year:"2018-19",name:"第34期十段位"},{year:"2023",name:"第25期麻雀マスターズ"},{year:"2022",name:"第24期麻雀マスターズ"},{year:"2021",name:"第28期發王位"}], bio: ["「戦闘民族」佐々木寿人。宮城県仙台市出身、1977年生まれ。東北学院大学中退後、2003年に日本プロ麻雀連盟第19期生としてプロ入り。","どこまでも押し続ける超攻撃型の雀風から「戦闘民族」と称される。十段位を5期以上、麻雀マスターズを複数期獲得するなど連盟トップクラスのタイトルホルダー。Mリーグには2018年発足時からKONAMI麻雀格闘倶楽部のメンバー。","趣味は桃鉄（桃太郎電鉄）。「放銃を恐れない」スタイルでファンからは愛されており、Mリーグでも常に上位の人気を誇る。"] },
  { id: "takamiya",   name: "高宮まり",    nameEn: "Mari Takamiya",       org: "JPML",  title: "女流桜花",       tags: ["女流","A1"],      league: "A1",    period: "第27期", joinYear: 2011, birthday: "1988/11/08", gender: "female", href: "/players/takamiya",    mleagueTeam: "KONAMI麻雀格闘倶楽部", birthplace: "茨城県", bloodType: "O型", hobby: "グラビア・麻雀", nickname: "まりあんぬ", bio: ["「まりあんぬ」高宮まり。茨城県出身、1988年生まれ。日本プロ麻雀連盟第27期生として2011年にプロ入り。グラビアアイドルとしても活動する、麻雀界屈指のビジュアル系女流雀士。","KONAMI麻雀格闘倶楽部のMリーガーとして2018年発足時から参加。女流桜花Aリーグにも在籍し、麻雀もグラビアもハイレベルをこなす。得意な局面での攻撃的な仕掛けが持ち味。","趣味は麻雀とグラビア活動。持ち前の明るいキャラクターでチームの雰囲気メーカー的存在でもある。"] },
  { id: "date",       name: "伊達朱里紗",  nameEn: "Arisa Date",          org: "JPML",  title: "女流桜花",       tags: ["女流","A1"],      league: "A1",    period: "第30期", joinYear: 2014, birthday: "1991/05/10", gender: "female", href: "/players/date",        mleagueTeam: "KONAMI麻雀格闘倶楽部", birthplace: "兵庫県三田市", bloodType: "B型", hobby: "水彩色鉛筆画・ライブ鑑賞", nickname: "夢見るセイレーン", bio: ["「夢見るセイレーン」伊達朱里紗。兵庫県三田市出身、1991年生まれ。声優・81プロデュース所属としても活動する二刀流プロ。立命館大学映像学部中退後、2014年に日本プロ麻雀連盟第30期生としてプロ入り。","2021年に第一期桜蕾戦優勝で初タイトル。2021-22シーズンよりKONAMI麻雀格闘倶楽部のMリーガーとして参加。声優としての感性を活かした表現豊かな麻雀スタイルでファンを魅了する。","趣味は水彩色鉛筆画とライブ鑑賞。アニメ「咲-Saki-」に影響を受けて麻雀の世界へ踏み込んだという。"] },
  { id: "takizawa",   name: "滝沢和典",    nameEn: "Kazunori Takizawa",   org: "JPML",  title: "王位×2",        tags: ["攻撃型","A1"],    league: "A1",    period: "第12期", joinYear: 1996, birthday: "1971/03/15", gender: "male",   href: "/players/takizawa",    mleagueTeam: "KONAMI麻雀格闘倶楽部", birthplace: "新潟県長岡市", bloodType: "B型", hobby: "ギター・お酒", nickname: "格闘倶楽部の職人", bio: ["「格闘倶楽部の職人」滝沢和典。新潟県長岡市出身、1979年生まれ。音楽系専門学校中退後、1996年に日本プロ麻雀連盟第12期生としてプロ入り。連盟理事、八段。","王位を2期連覇（第32・33期）するなど安定した実力を持つ職人型雀士。Mリーグには2018年発足時からKONAMI麻雀格闘倶楽部のメンバー。チームの精神的支柱として機能している。","趣味はギターとお酒。音楽的なセンスを麻雀のリズム感に活かす独特のスタイルが評価されている。"] },

  // ── EX風林火山 ──────────────────────────────────────────────
  { id: "nikaido-a",  name: "二階堂亜樹",  nameEn: "Aki Nikaido",         org: "JPML",  title: "女流桜花×3",     tags: ["女流","A1"],      league: "A1",    period: "第18期", joinYear: 2002, birthday: "1980/04/09", gender: "female", href: "/players/nikaido-a",   mleagueTeam: "EX風林火山", birthplace: "神奈川県鎌倉市", bloodType: "O型", hobby: "ドライブ・漫画", nickname: "卓上の舞姫", bio: ["「卓上の舞姫」二階堂亜樹。神奈川県鎌倉市出身、1981年生まれ。日本プロ麻雀連盟第15期生として1999年にプロ入り。姉・二階堂瑠美とともに活躍する麻雀界のパイオニア的女流雀士。","女流桜花を複数期獲得、2007・2008年と連覇も果たした。EX風林火山のMリーガーとして2018年発足時から参加。優雅な佇まいと鋭い一打が共存する「舞姫」の名にふさわしい雀士。","趣味はドライブと漫画。姉妹でともにMリーガーとして活躍した時代を持つ、連盟を代表するレジェンド女流プロ。"] },
  { id: "katsumata",  name: "勝又健志",    nameEn: "Kenji Katsumata",     org: "JPML",  title: "鳳凰位",        tags: ["論理派","A1"],    league: "A1",    period: "第17期", joinYear: 2001, birthday: "1981/03/15", gender: "male",   href: "/players/katsumata",   mleagueTeam: "EX風林火山", birthplace: "東京都墨田区", bloodType: "B型", hobby: "将棋・漫画", nickname: "天才軍師", titles: [{year:"2025-26",name:"第42期鳳凰位"},{year:"2020",name:"第32期鳳凰位"}], bio: ["「天才軍師」「麻雀IQ220」勝又健志。東京都墨田区出身、1981年生まれ。早稲田大学在学中の19歳で日本プロ麻雀連盟第17期生としてプロ入り。","2016年に第32期鳳凰位を最年少クラスで獲得し一躍注目を集める。2026年には第42期鳳凰位も獲得、Mリーグではチーム最高成績にも貢献。EX風林火山のメンバーとして2018年発足時から参加。","趣味は将棋と漫画。早大卒の知性と高い情報処理能力から「麻雀IQ220」と称される理論派で、データと感覚を融合させた現代麻雀の体現者。"] },
  { id: "nagai",      name: "永井孝典",    nameEn: "Kosuke Nagai",        org: "最高位戦", title: "最高位",       tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2008, birthday: "1986/08/10", gender: "male",   href: "/players/nagai",       mleagueTeam: "EX風林火山", birthplace: "愛知県田原市", bloodType: "B型", hobby: "競馬・野球観戦", nickname: "フッ軽雀士", bio: ["「フッ軽雀士」永井孝典。愛知県田原市出身、1986年生まれ。最高位戦日本プロ麻雀協会所属。関西を拠点にしながら全国のタイトル戦予選やプロアマ大会に積極参加する行動力が持ち味。","Mリーグには2024-25シーズンよりEX風林火山のメンバーとして参加。加入直後からトップを量産し、チームの勝利に大きく貢献した。","趣味は競馬と野球観戦。隣の豊橋市出身の鈴木優選手と同じ高校の先輩にあたるという縁も。"] },
  { id: "uchikawa",   name: "内川幸太郎",  nameEn: "Kotaro Uchikawa",     org: "JPML",  title: "最高位×2",      tags: ["A1"],            league: "A1",    period: "第21期", joinYear: 2005, birthday: "1981/05/06", gender: "male",   href: "/players/uchikawa",    mleagueTeam: "EX風林火山", birthplace: "長野県松本市", bloodType: "O型", hobby: "ポーカー", nickname: "マエストロ", titles: [{year:"2022-23",name:"第36期十段位"},{year:"2021-22",name:"第35期十段位"}], bio: ["「手順マエストロ」内川幸太郎。長野県松本市出身、1981年生まれ。長野県松本深志高校卒業後、21歳で雀荘経営を決意し経営者として活動。その後2005年に日本プロ麻雀連盟第21期生としてプロ入り。","十段位を2期連覇（第35・36期）するなどタイトルを複数獲得。正確な手順と読みの深さが特徴で「手順マエストロ」と称される。KADOKAWAサクラナイツに2018年発足時から参加し、2024-25シーズンからEX風林火山に移籍。","趣味はポーカー。論理的な思考を麻雀に活かし、チームの中核として長年活躍してきた。"] },

  // ── BEAST X ─────────────────────────────────────────────────
  { id: "suzuki-d",   name: "鈴木大介",    nameEn: "Daisuke Suzuki",      org: "JPML",  title: "十段位",        tags: ["棋士","A1"],      league: "A1",    period: "第10期", joinYear: 1994, birthday: "1974/07/11", gender: "male",   href: "/players/suzuki-d",    mleagueTeam: "BEAST X", birthplace: "東京都町田市", bloodType: "A型", hobby: "競馬・囲碁・ゴルフ", nickname: "二刀流ブルドーザー", bio: ["「二刀流ブルドーザー」鈴木大介。東京都町田市出身、1974年生まれ。将棋棋士（棋士番号213・九段）として長年活躍し、2023年に日本プロ麻雀連盟に入会した史上初の将棋・麻雀二刀流プロ。","将棋では1994年に20歳でプロ棋士となり、2023年に将棋の最高段位・九段に昇段。同年Mリーグドラフト会議でBEAST Xに指名され、麻雀プロとしてのMリーグデビューも果たした。","趣味は競馬・囲碁・ゴルフ。知性と経験が凝縮されたオーラで、二つのトップを極めた唯一の存在として注目を集め続けている。"] },
  { id: "nakata",     name: "中田花奈",    nameEn: "Kana Nakata",         org: "JPML",  title: "女流桜花",       tags: ["女流","アイドル"], league: "A1",    period: "第33期", joinYear: 2017, birthday: "1994/08/06", gender: "female", href: "/players/nakata",      mleagueTeam: "BEAST X", birthplace: "埼玉県", bloodType: "A型", hobby: "アイドル・ラジオ", nickname: "乃木坂の女流雀士", bio: ["「乃木坂の女流雀士」中田花奈。埼玉県出身、1994年生まれ。17歳で乃木坂46に加入し人気アイドルとして活躍。大学在学中に雀荘のアルバイトをきっかけに麻雀にのめり込み、卒業後の2017年に日本プロ麻雀連盟第33期生としてプロ入り。","Mリーグには2023-24シーズンよりBEAST Xのメンバーとして参加。アイドル時代のファンと麻雀ファン双方から愛される。東京・千駄木で雀荘カフェ「chun.」を経営するオーナー店長でもある。","趣味はアイドル鑑賞とラジオ。2024年には初タイトルを目指してリーグ戦でも奮闘中。"] },
  { id: "shimoishi",  name: "下石戟",     nameEn: "Geki Shimoishi",      org: "NPM",   title: "雀王",          tags: ["攻撃型"],         league: "A1",    period: "第13期", joinYear: 2014, birthday: "1987/03/20", gender: "male",   href: "/players/shimoishi",   mleagueTeam: "BEAST X", birthplace: "北海道苫小牧市", bloodType: "B型", hobby: "ビールを飲むこと", nickname: "逆襲の戟", bio: ["「逆襲の戟」下石戟。北海道苫小牧市出身、1987年生まれ。日本プロ麻雀協会第13期生（旧名：下井重貴）。2025-26シーズンに行われたBEAST Xのメンバー入替オーディションで優勝し、ドラフト指名を勝ち取った。","Mリーグには2025-26シーズンよりBEAST Xのメンバーとして参加。オーディションでは全国のプロ雀士と競い合い、その実力を証明した。協会の雀王戦にも参加し着実にキャリアを積んでいる。","趣味はビールを飲むこと。北海道出身らしい豪快さと、緻密な読みを両立させた雀風が持ち味。"] },
  { id: "tojo",       name: "東城りお",    nameEn: "Rio Tojo",            org: "JPML",  title: "女流桜花",       tags: ["女流","A1"],      league: "A1",    period: "第29期", joinYear: 2013, birthday: "1990/09/18", gender: "female", href: "/players/tojo",        mleagueTeam: "BEAST X", birthplace: "秋田県潟上市", bloodType: "O型", hobby: "ゲーム・アニメ", nickname: "全力乙女", bio: ["「全力乙女」東城りお。秋田県潟上市出身、1990年生まれ。日本プロ麻雀連盟第29期生として2013年にプロ入り。Mリーグには2021-22シーズンよりセガサミーフェニックスのメンバーとして参加し2024-25シーズンまで活躍。","2025-26シーズンよりBEAST Xに移籍。「全力乙女」の愛称どおり、持ち前の明るさと全力プレーでファンを魅了する。元フェニックスとしての経験を新天地で活かす。","趣味はゲームとアニメ。Mリーグ会場でも常に笑顔を絶やさず、チームの雰囲気を明るくする存在。"] },

  // ── 赤坂ドリブンズ ───────────────────────────────────────────
  { id: "sonoda",     name: "園田賢",     nameEn: "Ken Sonoda",          org: "最高位戦", title: "最高位",       tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2006, birthday: "1980/11/25", gender: "male",   href: "/players/sonoda",      mleagueTeam: "赤坂ドリブンズ", birthplace: "兵庫県神戸市", bloodType: "A型", hobby: "カラオケ・お酒", nickname: "孤高のデジタリスト", bio: ["「孤高のデジタリスト」園田賢。兵庫県神戸市出身、1980年生まれ。慶應義塾大学環境情報学部卒業という高学歴の持ち主。2003年に最高位戦日本プロ麻雀協会に入会（第28期後期）。","2017年にAリーグ昇級・決定戦進出を果たし、Mリーグには2018年発足時から赤坂ドリブンズのメンバーとして参加。データと論理に基づくデジタル系の雀風で、長期的な安定感と爆発力を兼ね備える。","趣味はカラオケとお酒。ExcelやスプレッドシートでのデータAIシステムを開発するなど、麻雀外でも知的好奇心を発揮している。"] },
  { id: "suzuki-t",   name: "鈴木たろう",  nameEn: "Taro Suzuki",         org: "最高位戦", title: "最高位×3",     tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 1999, birthday: "1973/10/04", gender: "male",   href: "/players/suzuki-t",    mleagueTeam: "赤坂ドリブンズ", birthplace: "茨城県水海道市", bloodType: "B型", hobby: "ポーカー・将棋", nickname: "最高位3冠", titles: [{year:"2021",name:"第44期最高位"},{year:"2017",name:"第41期最高位"},{year:"2010",name:"第35期最高位"}], bio: ["「最高位3冠」鈴木たろう。茨城県水海道市（現常総市）出身、1973年生まれ。高千穂大学卒業後、日本プロ麻雀棋士会・日本プロ麻雀協会を経て2020年11月に最高位戦日本プロ麻雀協会へ移籍。","最高位を3期獲得（第35・41・44期）したタイトルホルダー。Mリーグには2018年発足時から赤坂ドリブンズのメンバーとして参加。ポーカーや将棋も嗜む多彩な知性派雀士。","趣味はポーカーと将棋。「入会10年負け続けたが近年圧倒的な速度で勝ちを積み重ねている」と称される、遅咲きの実力者。"] },
  { id: "asami",      name: "浅見真紀",    nameEn: "Maki Asami",          org: "最高位戦", title: "最高位",       tags: ["女流","A"],       league: "Aリーグ", period: "第35期", joinYear: 2018, birthday: "1985/08/30", gender: "female", href: "/players/asami",       mleagueTeam: "赤坂ドリブンズ", birthplace: "埼玉県所沢市", bloodType: "O型", hobby: "似顔絵を描くこと", nickname: "聡明なるバイプレイヤー", bio: ["「聡明なるバイプレイヤー」浅見真紀。埼玉県所沢市出身、1985年生まれ。千葉大学大学院工学研究科デザイン科学専攻卒業という理系高学歴の持ち主。2010年に最高位戦日本プロ麻雀協会第35期前期生としてプロ入り。","Mリーグには2023-24シーズンより赤坂ドリブンズのメンバーとして参加。大学院で培った分析力を活かした論理的な打牌が特徴。国立大学院卒という知性とお酒好きなキャラクターのギャップも魅力。","趣味は似顔絵を描くこと。チームの「聡明なバイプレイヤー」として、安定した成績でドリブンズを支えている。"] },
  { id: "watanabe",   name: "渡辺太",     nameEn: "Futoshi Watanabe",    org: "最高位戦", title: "最高位",       tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2010, birthday: "1988/07/25", gender: "male",   href: "/players/watanabe",    mleagueTeam: "赤坂ドリブンズ", birthplace: "埼玉県さいたま市", bloodType: "A型", hobby: "カラオケ・将棋観戦", nickname: "麻雀シンギュラリティ", bio: ["「麻雀シンギュラリティ」渡辺太。埼玉県さいたま市出身、1988年生まれ。現役の医師でもある異色の経歴の持ち主。東京大学理科1類に現役合格・中退後、医学部へ再入学して医師免許取得。天鳳位にも3回到達した天才肌。","最高位戦日本プロ麻雀協会所属。Mリーグには赤坂ドリブンズのメンバーとして参加。医師・天鳳位・Mリーガーという三つの顔を持つ「麻雀シンギュラリティ」の異名は伊達ではない。","趣味はカラオケと将棋観戦。知性と実戦の両立を体現する存在として麻雀界でも独自のポジションを確立している。"] },

  // ── セガサミーフェニックス ────────────────────────────────────
  { id: "kayamori",   name: "茅森早香",    nameEn: "Sayaka Kayamori",     org: "最高位戦", title: "最高位",       tags: ["女流","A"],       league: "Aリーグ", period: "",     joinYear: 2006, birthday: "1985/04/01", gender: "female", href: "/players/kayamori",    mleagueTeam: "セガサミーフェニックス", birthplace: "北海道苫小牧市", bloodType: "B型", hobby: "猫を愛でること・ビール", nickname: "天才すぎるオンナ雀士", titles: [{year:"2013",name:"第11期女流最高位"},{year:"2009",name:"第2回女流モンド"}], bio: ["「天才すぎるオンナ雀士」茅森早香。北海道苫小牧市出身、1982年生まれ。北海道苫小牧西高校中退後、2001年に最高位戦日本プロ麻雀協会に入会。Mリーグ初年度から参加するセガサミーフェニックスの顔。","女流最高位第11期・女流モンド第2回など複数タイトルを獲得。2025-26シーズンよりフェニックスの選手兼任監督を務める。手役を主眼に置きつつ状況対応する独自のバランス型雀風が特徴。","趣味は猫を愛でることとビール。天才と呼ばれながらも庶民的なキャラクターで愛されている。"] },
  { id: "daigo",      name: "醍醐大",     nameEn: "Dai Daigo",           org: "最高位戦", title: "最高位×2",     tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2010, birthday: "1988/06/14", gender: "male",   href: "/players/daigo",       mleagueTeam: "セガサミーフェニックス", birthplace: "千葉県松戸市", bloodType: "O型", hobby: "将棋・人狼・サウナ", nickname: "孤高の探究者", titles: [{year:"2020",name:"第45期最高位"}], bio: ["「孤高の探究者」「先切り十段」醍醐大。千葉県松戸市出身、1976年生まれ。慶應義塾大学経済学部退学後、最高位戦日本プロ麻雀協会に入会（第30期前期）。中学から慶應に通った高学歴雀士。","2020年に第45期最高位を獲得。「先切り十段」の異名が示すように、バランス型でありながら独自の読みで牌を先切りするスタイルが持ち味。Mリーグには2020-21シーズンよりセガサミーフェニックスのメンバーとして参加。","趣味は将棋・人狼・サウナ。サラリーマン兼Mリーガーという二刀流で、川に落ちて足を骨折したエピソードも伝説。"] },
  { id: "takeuchi",   name: "竹内元太",    nameEn: "Genta Takeuchi",      org: "最高位戦", title: "最高位×2",     tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2012, birthday: "1986/03/12", gender: "male",   href: "/players/takeuchi",    mleagueTeam: "セガサミーフェニックス", birthplace: "長野県長野市", bloodType: "O型", hobby: "登山・ダジャレ", nickname: "無敵のタイタン", titles: [{year:"2023",name:"第48期最高位"},{year:"2022",name:"第47期最高位"}], bio: ["「無敵のタイタン」竹内元太。長野県長野市出身、1986年生まれ。大学中退後、2012年に最高位戦日本プロ麻雀協会に入会（第38期前期）。プロ入り10年目の2022年に一気に開花した遅咲きの最高位。","2022年に第47期最高位を獲得、2023年には第48期最高位で連覇を達成。Mリーグには2022-23シーズンよりセガサミーフェニックスのメンバーとして参加。最高位連覇により「無敵のタイタン」の称号を確立した。","趣味は登山とダジャレ。都内で麻雀教室「元太麻雀ラボ」を主宰し、麻雀普及にも力を入れている。"] },
  { id: "asai",       name: "浅井堂岐",    nameEn: "Doki Asai",           org: "NPM",   title: "雀竜位",        tags: ["二刀流"],         league: "A1",    period: "",      joinYear: 2012, birthday: "1985/12/24", gender: "male",   href: "/players/asai",        mleagueTeam: "セガサミーフェニックス", birthplace: "埼玉県熊谷市", bloodType: "O型", hobby: "ITエンジニアリング", nickname: "逆襲のヘラクレス", bio: ["「逆襲のヘラクレス」浅井堂岐。埼玉県熊谷市出身、1985年生まれ。大学卒業後、営業職として働きながら2010年に日本プロ麻雀協会に入会。その後ITエンジニアに転身し、現在はバレットグループでエンジニア兼プロ雀士として活躍する二刀流。","Mリーグには2022-23シーズンよりセガサミーフェニックスのメンバーとして参加。2022年に天鳳新設タイトル「皓王戦」初代優勝者となり「初代皓王位」の称号も持つ。","ITエンジニアとしての論理的思考を麻雀に活かすスタイルは「逆襲のヘラクレス」の異名とも相まって独自の存在感を放つ。"] },

  // ── 渋谷ABEMAS ───────────────────────────────────────────────
  { id: "taii",       name: "多井隆晴",    nameEn: "Takaharu Taii",       org: "RMU",   title: "代表",          tags: ["攻撃型","A"],     league: "Aリーグ", period: "",     joinYear: 2007, birthday: "1972/03/17", gender: "male",   href: "/players/taii",        mleagueTeam: "渋谷ABEMAS", birthplace: "東京都葛飾区", bloodType: "B型", hobby: "映画鑑賞・漫画・アニメ", nickname: "最強雀士", bio: ["「最強雀士」多井隆晴。東京都葛飾区出身、1972年生まれ。高校卒業後、日本プロ麻雀連盟を経てRMUを設立・代表を務める。連盟時代の経緯から独立し、新たな麻雀プロ団体・RMUを立ち上げた異色の経歴の持ち主。","RMU最高ランクのSSS級。Mリーグには2018年発足時から渋谷ABEMASのメンバーとして参加し、圧倒的な成績で「最強雀士」の異名を確立。メンゼンを主体にした攻撃的雀風と高い読み精度が持ち味。","趣味は映画鑑賞・漫画・アニメ。YouTuberとしても積極的に情報発信し、麻雀の普及・エンタメ化に大きく貢献している。"] },
  { id: "shiratori",  name: "白鳥翔",     nameEn: "Sho Shiratori",       org: "JPML",  title: "十段位",        tags: ["技巧派","A1"],    league: "A1",    period: "第22期", joinYear: 2006, birthday: "1983/10/04", gender: "male",   href: "/players/shiratori",   mleagueTeam: "渋谷ABEMAS", birthplace: "東京都練馬区", bloodType: "A型", hobby: "e-Sports", nickname: "麻雀ハイブリッド", titles: [{year:"2021-22",name:"第35期十段位"},{year:"2020-21",name:"第34期十段位"}], bio: ["「麻雀ハイブリッド」白鳥翔。東京都練馬区出身、1986年生まれ。慶應義塾大学商学部卒業後、2006年に日本プロ麻雀連盟第22期生としてプロ入り。現在は理事・八段。","2021年の第34期、2022年の第35期と十段位を連覇。2026年現在は現鳳凰位（第42期）。Mリーグには2018年発足時から渋谷ABEMASのメンバーとして参加。守備寄りのバランス型という「ハイブリッド」の名にふさわしい万能型雀士。","趣味はe-Sports。論理的な思考と高い守備力を兼ね備え、長年にわたってチームの柱として活躍している。"] },
  { id: "matsumoto",  name: "松本吉弘",    nameEn: "Yoshihiro Matsumoto", org: "NPM",   title: "雀王",          tags: ["二刀流"],         league: "A1",    period: "",      joinYear: 2012, birthday: "1991/03/28", gender: "male",   href: "/players/matsumoto",   mleagueTeam: "渋谷ABEMAS", birthplace: "神奈川県横浜市", bloodType: "O型", hobby: "お酒・カラオケ・ペット", nickname: "187cmの長身雀士", bio: ["「卓上のヒットマン」松本吉弘。神奈川県横浜市出身、1992年生まれ。身長187cmという高身長で存在感を放つ日本プロ麻雀協会第12期生後期。中学では中国語を専攻、大学では青山学院大学に進学した。","第25期發王位でタイトル初獲得。Mリーグには2018年発足時から渋谷ABEMASのメンバーとして参加。高身長から繰り出す鋭い打牌と「卓上のヒットマン」の異名が示す正確な攻撃が持ち味。","趣味はお酒・カラオケ・ペット（猫派）。明るいキャラクターとSNSでの発信力でファン層も幅広い。"] },
  { id: "hinata",     name: "日向藍子",    nameEn: "Aiko Hinata",         org: "最高位戦", title: "最高位",       tags: ["女流","A"],       league: "Aリーグ", period: "",     joinYear: 2009, birthday: "1988/09/24", gender: "female", href: "/players/hinata",      mleagueTeam: "渋谷ABEMAS", birthplace: "長野県茅野市", bloodType: "O型", hobby: "御朱印集め・ガンプラ", nickname: "ラブフェニックス", bio: ["「ラブフェニックス」日向藍子。長野県茅野市出身、1988年生まれ。服飾大学卒業後、2011年に最高位戦日本プロ麻雀協会に入会。19歳で麻雀と出会い、ほどなくプロを志した。","Mリーグには2019-20シーズンより渋谷ABEMASのメンバーとして参加。「ラブフェニックス」「小さなビッグマム」などの愛称を持ち、結婚・出産を経てもMリーガーとして活躍するママ雀士の先駆け。","趣味は御朱印集め・ガンプラ・フラワーアレンジメント。多彩な趣味と笑顔のキャラクターで幅広いファンから愛されている。"] },

  // ── KADOKAWAサクラナイツ ─────────────────────────────────────
  { id: "okada",      name: "岡田紗佳",    nameEn: "Sayaka Okada",        org: "JPML",  title: "女流桜花",       tags: ["女流","モデル"],  league: "A1",    period: "第32期", joinYear: 2016, birthday: "1994/02/19", gender: "female", href: "/players/okada",       mleagueTeam: "KADOKAWAサクラナイツ", birthplace: "東京都世田谷区", bloodType: "O型", hobby: "モデル・中国語", nickname: "完全武装アフロディーテ", bio: ["「完全武装アフロディーテ」岡田紗佳。東京都世田谷区出身、1994年生まれ。日中のハーフで中国語・日本語に堪能。青山学院大学国際経済政治学部卒。6歳から中国の小学校に通った国際派。","モデル・グラビアアイドルとしても活躍しながら、2016年に日本プロ麻雀連盟第32期生としてプロ入り。2018年発足時からKADOKAWAサクラナイツのメンバーとしてMリーグ参加。長身170cmのモデルが打つ攻撃的な麻雀が話題を呼んだ。","趣味はモデル活動と中国語。「才色兼備」の代名詞として麻雀界だけでなくメディア露出も多い人気選手。"] },
  { id: "hori",       name: "堀慎吾",     nameEn: "Shingo Hori",         org: "JPML",  title: "雀王×3",        tags: ["A1"],            league: "A1",    period: "第23期", joinYear: 2007, birthday: "1984/03/23", gender: "male",   href: "/players/hori",        mleagueTeam: "KADOKAWAサクラナイツ", birthplace: "新潟県新発田市", bloodType: "A型", hobby: "ゲーム・競馬・将棋", nickname: "小さな天才", titles: [{year:"2025",name:"Mトーナメント2025優勝"},{year:"2021-22",name:"第23期雀王"},{year:"2020-21",name:"第22期雀王"},{year:"2018-19",name:"第21期雀王"}], bio: ["「小さな天才」堀慎吾。新潟県新発田市出身、1984年生まれ、身長164cm。日本プロ麻雀協会第23期生（2010年入会）後に日本プロ麻雀連盟に移籍。","雀王を3期獲得（第21・22・23期）したタイトルホルダー。2025年にはMトーナメント2025で優勝。Mリーグには2018年発足時からKADOKAWAサクラナイツのメンバーとして参加。小柄な体格ながら「小さな天才」の異名どおり精度の高い麻雀を展開する。","趣味はゲーム・競馬・将棋。子供向けの麻雀教室も積極的に開催し、普及活動にも力を入れている。"] },
  { id: "shibukawa",  name: "渋川難波",    nameEn: "Nanba Shibukawa",     org: "最高位戦", title: "最高位",       tags: ["二刀流","A"],     league: "Aリーグ", period: "",     joinYear: 2008, birthday: "1986/05/19", gender: "male",   href: "/players/shibukawa",   mleagueTeam: "KADOKAWAサクラナイツ", birthplace: "広島県廿日市市", bloodType: "A型", hobby: "麻雀研究", nickname: "魔神", bio: ["「魔神」渋川難波。広島県廿日市市出身、1986年生まれ。日本プロ麻雀協会第10期前期生として入会後、2022-23シーズンより最高位戦日本プロ麻雀協会へ移籍。協会のグランドスラム（雀竜位・日本オープン・雀王の全制覇）を達成した実力者。","Mリーグには2022-23シーズンよりKADOKAWAサクラナイツのメンバーとして参加。「魔神」の異名が示す圧倒的な攻撃力と読みの深さで、チームに不可欠な存在となっている。","麻雀研究に打ち込む姿勢から「魔神」と称される。YouTubeでの対局解説も好評で、普及活動にも貢献。"] },
  { id: "akutsu",     name: "阿久津翔太",  nameEn: "Shota Akutsu",        org: "JPML",  title: "A1リーグ",       tags: ["A1"],            league: "A1",    period: "第34期", joinYear: 2018, birthday: "1996/04/23", gender: "male",   href: "/players/akutsu",      mleagueTeam: "KADOKAWAサクラナイツ", birthplace: "茨城県日立市", hobby: "麻雀研究", nickname: "若獅子", bio: ["「若獅子」阿久津翔太。茨城県日立市出身、1996年生まれ。6歳で麻雀プロになることを目標に設定したという生粋の麻雀エリート。埼玉大学情報工学科進学後、卒業前に雀荘勤務を経て2018年に日本プロ麻雀連盟第34期生としてプロ入り。","第1期若獅子戦優勝で初タイトル。2024-25シーズンよりKADOKAWAサクラナイツのMリーガーとして参加。2025-26シーズンも継続参加し、チームの若手エースとして期待を集める。","麻雀研究と実戦を両立させた現代型の雀士。「若獅子」の名にふさわしい勢いと将来性がある。"] },

  // ── U-NEXT Pirates ──────────────────────────────────────────
  { id: "kobayashi",  name: "小林剛",     nameEn: "Go Kobayashi",        org: "μ",     title: "王将位",        tags: ["理論派","A"],     league: "Aリーグ", period: "",     joinYear: 2003, birthday: "1976/02/12", gender: "male",   href: "/players/kobayashi",   mleagueTeam: "U-NEXT Pirates", birthplace: "東京都八王子市", bloodType: "AB型", hobby: "カラオケ", nickname: "麻将連合の理論派", bio: ["「麻将連合の理論派」小林剛。東京都八王子市出身、1976年生まれ。東京理科大学理学部数学科中退後、麻将連合（μ）の前身組織に入会し現在も麻将連合所属。","王将位をはじめ複数タイトルを保持。Mリーグには2018年発足時からU-NEXT Piratesのメンバーとして参加。数学的バックグラウンドを活かした論理的な雀風で、リーグ内屈指の安定感を誇る。著書も複数持つ論客。","趣味はカラオケ。著書「小林剛の麻雀必勝法」など執筆活動も精力的に行い、麻雀の理論・普及にも貢献している。"] },
  { id: "mizuhara",   name: "瑞原明奈",    nameEn: "Akina Mizuhara",      org: "最高位戦", title: "最高位",       tags: ["女流","A"],       league: "Aリーグ", period: "",     joinYear: 2009, birthday: "1986/11/19", gender: "female", href: "/players/mizuhara",    mleagueTeam: "U-NEXT Pirates", birthplace: "長崎県佐世保市", bloodType: "O型", hobby: "映画鑑賞・人狼", nickname: "早大出身の女流エース", bio: ["「早大出身の女流エース」瑞原明奈。長崎県佐世保市出身、1986年生まれ。長崎県立佐世保西高校卒業後、早稲田大学国際教養学部に進学。大学在学中にMONDO TVの麻雀番組を見て競技麻雀の世界へ入った。","最高位戦日本プロ麻雀協会所属（2017年移籍）。女流最高位も獲得し、2021-22シーズンにはMリーグ個人タイトルも受賞。U-NEXT Piratesのメンバーとして2018年発足時から参加し、女性Mリーガー屈指の実力者として評価されている。","趣味は映画鑑賞と人狼。結婚・出産を経てもMリーガーとして活躍し続けるロールモデル的存在。"] },
  { id: "suzuki-y",   name: "鈴木優",     nameEn: "Yu Suzuki",           org: "最高位戦", title: "最高位",       tags: ["A"],             league: "Aリーグ", period: "第36期", joinYear: 2017, birthday: "1981/09/13", gender: "male",   href: "/players/suzuki-y",    mleagueTeam: "U-NEXT Pirates", birthplace: "愛知県豊橋市", bloodType: "O型", hobby: "お酒・カラオケ", nickname: "最強戦の申し子", bio: ["「最強戦の申し子」鈴木優。愛知県豊橋市出身、1981年生まれ。地元大学中退後、雀荘経営を経て最高位戦日本プロ麻雀協会に入会（第36期前期）。地元に「マナーの良い雀荘を作りたい」という思いから雀荘を立ち上げた実業家でもある。","麻雀最強戦で特に強さを発揮し「最強戦の申し子」と称される。U-NEXT Piratesのメンバーとして2020-21シーズンよりMリーグ参加。安定した成績でチームに貢献し続けている。","趣味はお酒とカラオケ。愛知県豊橋市から全国区の舞台へ飛び出した地方発のMリーガーとして、地元ファンからも熱い支持を受けている。"] },
  { id: "nakabayashi",name: "仲林圭",     nameEn: "Kei Nakabayashi",     org: "NPM",   title: "雀竜位",        tags: ["A1"],            league: "A1",    period: "第8期",  joinYear: 2009, birthday: "1987/04/22", gender: "male",   href: "/players/nakabayashi", mleagueTeam: "U-NEXT Pirates", birthplace: "東京都武蔵野市", bloodType: "O型", hobby: "フットサル", nickname: "海賊の司令塔", bio: ["「海賊の司令塔」仲林圭。東京都武蔵野市出身、1985年生まれ（本名：中林啓）。早稲田大学理工学部コンピュータ・ネットワーク工学科中退後、日本プロ麻雀協会第7期前期生としてプロ入り。","第10期雀竜位をはじめタイトルを複数獲得。麻雀界きってのゲス雀士として独自の個性を発揮しつつ、「海賊の書（共著）」なども出版。U-NEXT Piratesのメンバーとして2018年発足時から参加。","趣味はフットサル。身長176cmの体格から繰り出す大胆な攻めと独特のキャラクターで存在感を放つ、Pirates欠かせない個性派。"] },

  // ── EARTH JETS ──────────────────────────────────────────────
  { id: "ishii",      name: "石井一馬",    nameEn: "Kazuma Ishii",        org: "最高位戦", title: "最高位",       tags: ["A"],             league: "Aリーグ", period: "",     joinYear: 2006, birthday: "1986/02/21", gender: "male",   href: "/players/ishii",       mleagueTeam: "EARTH JETS", birthplace: "東京都", bloodType: "A型", hobby: "ゲーム", nickname: "データ派の刺客", titles: [{year:"2024",name:"第49期最高位"}], bio: ["「データ派の刺客」石井一馬。東京都出身、1986年生まれ。2006年、19歳で最高位戦日本プロ麻雀協会に入会。中学生から麻雀データ分析に取り組んできた理論派。","2024年に第49期最高位を獲得。速く鋭い攻撃を武器に20代から数々のビッグタイトルで上位進出を続け、Mリーグには2025-26シーズンよりEARTH JETSメンバーとして参加。","趣味はゲーム。データと感覚を融合させた独自の雀風でMリーグでも存在感を発揮している。"] },
  { id: "miura",      name: "三浦智博",    nameEn: "Tomohiro Miura",      org: "JPML",  title: "十段位×2",      tags: ["A1"],            league: "A1",    period: "第28期", joinYear: 2012, birthday: "1987/04/26", gender: "male",   href: "/players/miura",       mleagueTeam: "EARTH JETS", birthplace: "愛知県小牧市", hobby: "麻雀研究", nickname: "実戦5万半荘の感覚派", titles: [{year:"2024-25",name:"第41期十段位"},{year:"2023-24",name:"第40期十段位"},{year:"2023",name:"第48期王位"}], bio: ["「実戦5万半荘の感覚派」三浦智博。愛知県小牧市出身、1987年生まれ。名古屋工業大学中退後、2012年に日本プロ麻雀連盟第28期生としてプロ入り。","プロ入り11年目となる2023年、第40期十段位で初タイトルを獲得。翌2023年に第48期王位、2024年には十段位を連覇（第41期）と、30代後半でついに覚醒。Mリーグには2025-26シーズンよりEARTH JETSメンバーとして参加。","連盟公式ルールで鍛えられた打点力に自信を持つ攻撃型。5万半荘以上の実戦経験から磨かれた感覚打ちで対戦相手を圧倒する。"] },
  { id: "aikawa",     name: "逢川恵夢",    nameEn: "Megumu Aikawa",       org: "NPM",   title: "永世女流雀王",   tags: ["女流","A1"],      league: "A1",    period: "第1期",  joinYear: 2002, birthday: "1987/08/28", gender: "female", href: "/players/aikawa",      mleagueTeam: "EARTH JETS", birthplace: "大阪府", hobby: "麻雀研究", nickname: "永世女流雀王", titles: [{year:"2023",name:"第18期女流雀王（永世称号）"}], bio: ["「永世女流雀王」逢川恵夢。大阪府出身、1987年生まれ。2002年、令和元年生まれを自称（本人談）。2011年に日本プロ麻雀協会に入会、第10期新人王戦を優勝してプロデビュー。","女流雀王のタイトルを通算10期以上獲得し、永世女流雀王の称号を持つ唯一の雀士。2023年には第18期女流雀王で最後のタイトルを獲得し永世称号を確定させた。Mリーグには2025-26シーズンよりEARTH JETSメンバーとして参加。","軽快な鳴き麻雀と柔軟な手組みが持ち味。長野市出身で「令和元年生まれ」というキャラクター設定も愛されている。"] },
  { id: "hiro-shibata",name: "HIRO柴田",  nameEn: "Hiro Shibata",        org: "JPML",  title: "A1リーグ",       tags: ["A1"],            league: "A1",    period: "第16期", joinYear: 2000, birthday: "1976/02/16", gender: "male",   href: "/players/hiro-shibata",mleagueTeam: "EARTH JETS", birthplace: "神奈川県川崎市", bloodType: "A型", hobby: "お笑い・ゲーム・漫画", nickname: "連盟の九段", titles: [{year:"2022",name:"第39期鳳凰位"},{year:"2016",name:"第13期グランプリMAX"},{year:"2015",name:"第14期グランプリMAX"}], bio: ["「連盟の九段」HIRO柴田。神奈川県川崎市出身、1976年生まれ。大学中退後に雀荘勤務を経て2000年に日本プロ麻雀連盟に入会、2001年に第17期生としてプロデビュー。旧名は柴田弘幸。","連盟最高段位の九段に到達した実力者で、2022年には団体最高峰タイトルの第39期鳳凰位を獲得。Mリーグには2025-26シーズンよりEARTH JETSの新規メンバーとして参加した。","趣味はお笑い・ゲーム・漫画と幅広く、YouTubeでも積極的に発信。麻雀教室も主宰し、普及にも力を入れている。"] },

  // ── Mリーグ外 ────────────────────────────────────────────────
  { id: "maehara",    name: "前原雄大",    nameEn: "Yudai Maehara",       org: "JPML",  title: "鳳凰位×5",      tags: ["攻撃型","A1"],    league: "A1",    period: "第3期",  joinYear: 1987, birthday: "1963/05/28", gender: "male",   href: "/players/maehara" },
  { id: "nikaido-r",  name: "二階堂瑠美",  nameEn: "Rumi Nikaido",        org: "JPML",  title: "女流桜花",       tags: ["女流","A2"],      league: "A2",    period: "第18期", joinYear: 2002, birthday: "1982/07/18", gender: "female", href: "/players/nikaido-r" },
  { id: "uotani",     name: "魚谷侑未",    nameEn: "Yumi Uotani",         org: "NPM",   title: "雀王",          tags: ["女流","A1"],      league: "A1",    period: "第5期",  joinYear: 2006, birthday: "1985/07/07", gender: "female", href: "/players/uotani" },
  { id: "kondo",      name: "近藤誠一",    nameEn: "Seiichi Kondo",       org: "最高位戦", title: "最高位×7",     tags: ["レジェンド"],     league: "Aリーグ", period: "",     joinYear: 1990, birthday: "1966/08/22", gender: "male",   href: "/players/kondo" },
  { id: "iida",       name: "飯田正人",    nameEn: "Masato Iida",         org: "最高位戦", title: "最高位×9",     tags: ["レジェンド"],     league: "Aリーグ", period: "",     joinYear: 1985, birthday: "1960/05/10", gender: "male",   href: "/players/iida" },
  { id: "suda",       name: "須田良規",    nameEn: "Yoshinori Suda",      org: "μ",     title: "王将位",        tags: ["理論派","A"],     league: "Aリーグ", period: "",     joinYear: 2003, birthday: "1981/04/17", gender: "male",   href: "/players/suda" },
  { id: "miyauchi",   name: "宮内こずえ",  nameEn: "Kozue Miyauchi",      org: "μ",     title: "A1リーグ",       tags: ["女流","A"],       league: "Aリーグ", period: "",     joinYear: 2005, birthday: "1984/12/25", gender: "female", href: "/players/miyauchi" },
];
