// app/titles/data.ts
// 主要タイトル戦データ。2026-05-04時点で各団体公式ページを確認し、未確認の細部は断定しない。

export type OrgCode = "JPML" | "NPM" | "SAIKOUISEN" | "RMU" | "MU";

export interface PastChampion {
  ep: string;
  year: string;
  name: string;
  href?: string;
  note?: string;
  current?: boolean;
  pts?: string;
}

export interface CrownRankingEntry {
  name: string;
  count: number;
  href?: string;
}

export interface RuleRow {
  label: string;
  value: string;
}

export interface LeagueTier {
  code: string;
  title: string;
  desc: string;
  highlight?: boolean;
}

export interface TitleData {
  slug: string;
  href: string;
  code: string;
  name: string;
  shortName?: string;
  en: string;
  glyph: string;
  color: string;
  org: OrgCode;
  orgLabel: string;
  orgHref: string;
  holder?: { name: string; href?: string; note?: string };
  season: string;
  tags: string[];
  founded?: number;
  formatLabel: string;
  about: string[];
  rules?: RuleRow[];
  leagueTiers?: LeagueTier[];
  pastChampions: PastChampion[];
  crownRanking?: CrownRankingEntry[];
  relatedTitles?: { slug: string; name: string }[];
}

const JPML_OFFICIAL_RULES: RuleRow[] = [
  { label: "採用ルール", value: "日本プロ麻雀連盟公式ルール" },
  { label: "一発・裏ドラ", value: "なし" },
  { label: "カンドラ", value: "なし" },
  { label: "喰いタン・後付け", value: "あり" },
  { label: "途中流局", value: "なし" },
  { label: "同時ロン", value: "上家優先" },
];

const NPM_RULES: RuleRow[] = [
  { label: "採用ルール", value: "日本プロ麻雀協会公式ルール" },
  { label: "持ち点", value: "25,000点持ち30,000点返し" },
  { label: "順位点", value: "+50 / +10 / △10 / △30" },
  { label: "一発・裏ドラ", value: "あり" },
  { label: "カンドラ", value: "あり" },
  { label: "喰いタン・先付け", value: "あり" },
  { label: "親の連荘", value: "アガリ・テンパイ連荘" },
  { label: "途中流局", value: "なし" },
];

const SAIKOUISEN_RULES: RuleRow[] = [
  { label: "採用ルール", value: "最高位戦ルール" },
  { label: "持ち点", value: "30,000点持ち30,000点返し" },
  { label: "オカ", value: "なし" },
  { label: "ウマ", value: "10-30" },
  { label: "一発・裏ドラ", value: "あり" },
  { label: "カンドラ・カン裏", value: "あり" },
  { label: "喰いタン・先付け", value: "あり" },
  { label: "途中流局", value: "なし" },
];

const SAIKOUISEN_CLASSIC_RULES: RuleRow[] = [
  { label: "採用ルール", value: "最高位戦Classicルール" },
  { label: "順位点", value: "+12 / +4 / △4 / △12" },
  { label: "ドラ", value: "最初の一種類のみ" },
  { label: "一発・裏ドラ", value: "なし" },
  { label: "ノーテン罰符", value: "なし" },
  { label: "連荘", value: "親のアガリのみ" },
  { label: "喰い替え", value: "現物喰い替えあり" },
  { label: "リーチ後暗槓", value: "不可" },
];

const RMU_A_RULES: RuleRow[] = [
  { label: "採用ルール", value: "RMU公式Aルール" },
  { label: "持ち点", value: "30,000点持ち30,000点返し" },
  { label: "順位点", value: "+15 / +5 / △5 / △15" },
  { label: "一発・裏ドラ", value: "あり" },
  { label: "カンドラ・カン裏", value: "あり" },
  { label: "喰いタン・先付け", value: "あり" },
  { label: "親の連荘", value: "アガリ・テンパイ連荘" },
  { label: "途中流局", value: "なし" },
];

const RMU_B_RULES: RuleRow[] = [
  { label: "採用ルール", value: "RMU公式Bルール" },
  { label: "基準", value: "Aルールから一発・裏ドラ・カンドラを除く" },
  { label: "順位点", value: "+15 / +5 / △5 / △15" },
  { label: "持ち点", value: "30,000点持ち30,000点返し" },
  { label: "喰いタン・先付け", value: "あり" },
  { label: "途中流局", value: "なし" },
];

const MU_LEAGUE_RULES: RuleRow[] = [
  { label: "採用ルール", value: "μリーグルール" },
  { label: "テンパイ料", value: "なし" },
  { label: "順位点", value: "+12 / +4 / △4 / △12" },
  { label: "形式", value: "1節5回戦・全10節" },
  { label: "対象", value: "期首順位上位10名のプロ" },
  { label: "決定戦", value: "上位3名が現将王への挑戦権" },
];

const MU_CUP_RULES: RuleRow[] = [
  { label: "採用ルール", value: "μカップルール準拠" },
  { label: "順位点", value: "+12 / +4 / △4 / △12" },
  { label: "一発・裏ドラ", value: "なし" },
  { label: "形式", value: "大会規定による半荘戦" },
  { label: "対象", value: "会員・一般参加を含むオープン枠あり" },
];

export const TITLES: TitleData[] = [
  {
    slug: "houou-isen",
    href: "/titles/houou-isen",
    code: "01 · HŌŌI",
    name: "鳳凰戦",
    shortName: "鳳凰位",
    en: "The Hōōi Championship",
    glyph: "鳳",
    color: "var(--vermilion)",
    org: "JPML",
    orgLabel: "日本プロ麻雀連盟",
    orgHref: "/organizations/jpml",
    holder: { name: "白鳥 翔", href: "/players/shiratori", note: "第42期 (2026)" },
    season: "A1・A2は年間、B以下は半期制",
    tags: ["JPML最高峰", "リーグ戦", "公式ルール"],
    founded: 1984,
    formatLabel: "A〜Eリーグ + 鳳凰位決定戦",
    about: [
      "鳳凰戦は日本プロ麻雀連盟の最高峰リーグ戦。A〜Eの各リーグで昇降級を行い、A1上位者と現鳳凰位が決定戦で鳳凰位を争う。",
      "連盟公式の開催概要では、A1は12名で、その年の上位3名と前年度鳳凰位が4日間・半荘16回を戦う形式とされている。",
      "採用ルールは日本プロ麻雀連盟公式ルール。一発・裏ドラなしの重厚な競技ルールで争われる。",
    ],
    rules: [...JPML_OFFICIAL_RULES, { label: "決定戦", value: "4日間・半荘16回" }],
    leagueTiers: [
      { code: "A1", title: "最高峰", desc: "上位者が鳳凰位決定戦へ", highlight: true },
      { code: "A2", title: "上位リーグ", desc: "A1昇級を争う年間リーグ" },
      { code: "B", title: "中位リーグ", desc: "半期ごとの昇降級" },
      { code: "C", title: "育成層", desc: "半期ごとの昇降級" },
      { code: "D/E", title: "登竜門", desc: "連盟所属プロの入口" },
    ],
    pastChampions: [
      { ep: "42", year: "2025", name: "白鳥翔", current: true },
      { ep: "41", year: "2024", name: "白鳥翔" },
      { ep: "40", year: "2023", name: "佐々木寿人" },
      { ep: "39", year: "2022", name: "HIRO柴田" },
      { ep: "38", year: "2021", name: "佐々木寿人" },
      { ep: "37", year: "2020", name: "佐々木寿人" },
      { ep: "36", year: "2019", name: "藤崎智" },
      { ep: "35", year: "2018", name: "吉田直" },
      { ep: "34", year: "2017", name: "前原雄大" },
      { ep: "33", year: "2016", name: "前原雄大" },
      { ep: "32", year: "2015", name: "勝又健志" },
      { ep: "31", year: "2014", name: "前田直哉" },
      { ep: "30", year: "2013", name: "藤崎智" },
      { ep: "29", year: "2012", name: "瀬戸熊直樹" },
      { ep: "28", year: "2011", name: "荒正義" },
      { ep: "27", year: "2010", name: "瀬戸熊直樹" },
      { ep: "26", year: "2009", name: "瀬戸熊直樹" },
      { ep: "25", year: "2008", name: "前原雄大" },
      { ep: "24", year: "2007", name: "朝武雅晴" },
      { ep: "23", year: "2006", name: "望月雅継" },
      { ep: "22", year: "2005", name: "土田浩翔" },
      { ep: "21", year: "2004", name: "阿部孝則" },
      { ep: "20", year: "2003", name: "阿部孝則" },
      { ep: "19", year: "2002", name: "阿部孝則" },
      { ep: "18", year: "2001", name: "古川孝次" },
      { ep: "17", year: "2000", name: "古川孝次" },
      { ep: "16", year: "1999", name: "古川孝次" },
      { ep: "15", year: "1998", name: "石崎洋" },
      { ep: "14", year: "1997", name: "原田正史" },
      { ep: "13", year: "1996", name: "森谷健" },
      { ep: "12", year: "1995", name: "前原雄大" },
      { ep: "11", year: "1994", name: "土田浩翔" },
      { ep: "10", year: "1993", name: "安藤満" },
      { ep: "9", year: "1992", name: "伊藤優孝" },
      { ep: "8", year: "1991", name: "荒正義" },
      { ep: "7", year: "1990", name: "椎名大介" },
      { ep: "6", year: "1989", name: "安藤満" },
      { ep: "5", year: "1988", name: "安藤満" },
      { ep: "4", year: "1987", name: "島田昭" },
      { ep: "3", year: "1986", name: "ロッキー堀江" },
      { ep: "2", year: "1985", name: "安藤満" },
      { ep: "1", year: "1984", name: "島田昭" },
    ],
    crownRanking: [
      { name: "前原 雄大", count: 4 },
      { name: "安藤 満", count: 4 },
      { name: "佐々木 寿人", href: "/players/sasaki", count: 3 },
      { name: "瀬戸熊 直樹", href: "/players/setokuma", count: 3 },
      { name: "阿部 孝則", count: 3 },
    ],
    relatedTitles: [
      { slug: "judan-isen", name: "十段戦" },
      { slug: "oui-isen", name: "王位戦" },
    ],
  },
  {
    slug: "judan-isen",
    href: "/titles/judan-isen",
    code: "02 · JŪDAN",
    name: "十段戦",
    shortName: "十段位",
    en: "The Jūdan Championship",
    glyph: "十",
    color: "var(--vermilion)",
    org: "JPML",
    orgLabel: "日本プロ麻雀連盟",
    orgHref: "/organizations/jpml",
    holder: { name: "浜野 太陽", note: "第42期 (2025)" },
    season: "段位別トーナメント",
    tags: ["JPML", "トーナメント", "連盟プロ限定"],
    founded: 1984,
    formatLabel: "段位別トーナメント + 現十段位を交えた決定戦",
    about: [
      "十段戦は、連盟の段位制に基づいて行われるトーナメント形式のタイトル戦。",
      "初段戦から段位別に勝ち上がり、最終的に勝ち残った4名と現十段位の5名で決定戦を行う。",
      "ルールは日本プロ麻雀連盟公式ルール。連盟所属プロだけが挑む、段位制度と強く結びついたタイトル戦。",
    ],
    rules: [...JPML_OFFICIAL_RULES, { label: "決定戦", value: "勝ち上がり4名 + 現十段位" }],
    pastChampions: [
      { ep: "42", year: "2025", name: "浜野太陽", current: true },
      { ep: "41", year: "2024", name: "三浦智博" },
      { ep: "40", year: "2023", name: "三浦智博" },
      { ep: "39", year: "2022", name: "魚谷侑未" },
      { ep: "38", year: "2021", name: "荒正義" },
      { ep: "37", year: "2020", name: "柴田吉和" },
      { ep: "36", year: "2019", name: "伊藤優孝" },
      { ep: "35", year: "2018", name: "内川幸太郎" },
      { ep: "34", year: "2017", name: "藤崎智" },
      { ep: "33", year: "2016", name: "藤崎智" },
      { ep: "32", year: "2015", name: "柴田吉和" },
      { ep: "31", year: "2014", name: "櫻井秀樹" },
      { ep: "30", year: "2013", name: "瀬戸熊直樹" },
      { ep: "29", year: "2012", name: "瀬戸熊直樹" },
      { ep: "28", year: "2011", name: "瀬戸熊直樹" },
      { ep: "27", year: "2010", name: "堀内正人" },
      { ep: "26", year: "2009", name: "前原雄大" },
      { ep: "25", year: "2008", name: "前原雄大" },
      { ep: "24", year: "2007", name: "前原雄大" },
      { ep: "23", year: "2006", name: "土田浩翔" },
      { ep: "22", year: "2005", name: "土田浩翔" },
      { ep: "21", year: "2004", name: "河野高志" },
      { ep: "20", year: "2003", name: "河野高志" },
      { ep: "19", year: "2002", name: "河野高志" },
      { ep: "18", year: "2001", name: "石崎洋" },
      { ep: "17", year: "2000", name: "灘麻太郎" },
      { ep: "16", year: "1999", name: "藤崎智" },
      { ep: "15", year: "1998", name: "前原雄大" },
      { ep: "14", year: "1997", name: "前原雄大" },
      { ep: "13", year: "1996", name: "沢崎誠" },
      { ep: "12", year: "1995", name: "田中利春" },
      { ep: "11", year: "1994", name: "田中利春" },
      { ep: "10", year: "1993", name: "石崎洋" },
      { ep: "9", year: "1992", name: "灘麻太郎" },
      { ep: "8", year: "1991", name: "石崎洋" },
      { ep: "7", year: "1990", name: "滝石潤" },
      { ep: "6", year: "1989", name: "安藤満" },
      { ep: "5", year: "1988", name: "瀬田一輝" },
      { ep: "4", year: "1987", name: "畑正憲" },
      { ep: "3", year: "1986", name: "畑正憲" },
      { ep: "2", year: "1985", name: "鈴木ひろし" },
      { ep: "1", year: "1984", name: "畑正憲" },
    ],
    crownRanking: [
      { name: "前原 雄大", count: 5 },
      { name: "藤崎 智", count: 3 },
      { name: "瀬戸熊 直樹", href: "/players/setokuma", count: 3 },
      { name: "河野 高志", count: 3 },
      { name: "石崎 洋", count: 3 },
    ],
    relatedTitles: [
      { slug: "houou-isen", name: "鳳凰戦" },
      { slug: "oui-isen", name: "王位戦" },
    ],
  },
  {
    slug: "oui-isen",
    href: "/titles/oui-isen",
    code: "03 · ŌI",
    name: "王位戦",
    shortName: "王位",
    en: "The Ōi Championship",
    glyph: "王",
    color: "var(--vermilion)",
    org: "JPML",
    orgLabel: "日本プロ麻雀連盟",
    orgHref: "/organizations/jpml",
    holder: { name: "石川 正明", note: "第50期 (2025)" },
    season: "秋〜冬 · プロアマ混合オープン",
    tags: ["JPML", "オープン", "公式ルール"],
    founded: 1973,
    formatLabel: "プロ・アマ混合予選 → 本戦 → 決勝",
    about: [
      "王位戦は1973年に創設されたプロ・アマ混合の歴史あるオープンタイトル戦。1989年から日本プロ麻雀連盟主催で行われている。",
      "一般予選・プロ予選から本戦へ進み、上位者が決勝へ進出する。第50期の案内でも、プロ・アマ混合で実力日本一を競うタイトルとして募集されている。",
      "採用ルールは日本プロ麻雀連盟公式ルール。公式案内では一発・裏ドラなしと明記されている。",
    ],
    rules: [...JPML_OFFICIAL_RULES, { label: "参加", value: "プロ・アマ混合" }],
    pastChampions: [
      { ep: "50", year: "2025", name: "石川正明", current: true },
      { ep: "49", year: "2024", name: "福島佑一" },
      { ep: "48", year: "2023", name: "三浦智博" },
      { ep: "47", year: "2022", name: "石井良樹" },
      { ep: "46", year: "2021", name: "渡辺史哉" },
      { ep: "45", year: "2019", name: "森下剛任" },
      { ep: "44", year: "2018", name: "魚谷侑未" },
      { ep: "43", year: "2017", name: "野方祐介" },
      { ep: "42", year: "2016", name: "樋口 徹" },
      { ep: "41", year: "2015", name: "石井一馬" },
      { ep: "40", year: "2014", name: "清原継光" },
      { ep: "39", year: "2013", name: "森下剛任" },
      { ep: "38", year: "2012", name: "二見大輔" },
      { ep: "37", year: "2011", name: "緒方剛" },
      { ep: "36", year: "2010", name: "井出一寛" },
      { ep: "35", year: "2009", name: "坂本健二" },
      { ep: "34", year: "2008", name: "大橋良弘" },
      { ep: "33", year: "2007", name: "滝沢和典" },
      { ep: "32", year: "2006", name: "滝沢和典" },
      { ep: "31", year: "2005", name: "多井隆晴" },
      { ep: "30", year: "2004", name: "宮崎和樹" },
      { ep: "29", year: "2003", name: "荒正義" },
      { ep: "28", year: "2002", name: "宮岡宏樹" },
      { ep: "27", year: "2001", name: "清水香織" },
      { ep: "26", year: "2000", name: "土田浩翔、高橋利典" },
      { ep: "25", year: "1999", name: "鈴木譲" },
      { ep: "24", year: "1998", name: "井光一郎" },
      { ep: "23", year: "1997", name: "羽山真生" },
      { ep: "22", year: "1996", name: "羽山真生" },
      { ep: "21", year: "1995", name: "三好達也" },
      { ep: "20", year: "1993", name: "野吹敬三" },
      { ep: "19", year: "1992", name: "新津潔" },
      { ep: "18", year: "1991", name: "中島啓之" },
      { ep: "17", year: "1990", name: "飯田正人" },
      { ep: "16", year: "1989", name: "安藤満" },
      { ep: "15", year: "1988", name: "曽我秀一" },
      { ep: "14", year: "1987", name: "田中幸夫" },
      { ep: "13", year: "1985", name: "灘麻太郎" },
      { ep: "12", year: "1984", name: "灘麻太郎" },
      { ep: "11", year: "1983", name: "灘麻太郎" },
      { ep: "10", year: "1982", name: "灘麻太郎" },
      { ep: "9", year: "1981", name: "森山茂和" },
      { ep: "8", year: "1980", name: "原田進" },
      { ep: "7", year: "1979", name: "大類達夫" },
      { ep: "6", year: "1978", name: "深野浩士" },
      { ep: "5", year: "1977", name: "荒正義" },
      { ep: "4", year: "1976", name: "小原亮弘" },
      { ep: "3", year: "1975", name: "田中貞行" },
      { ep: "2", year: "1974", name: "青木博" },
      { ep: "1", year: "1973", name: "青木博" },
    ],
    crownRanking: [
      { name: "灘 麻太郎", count: 4 },
      { name: "滝沢 和典", href: "/players/takizawa", count: 2 },
      { name: "森下 剛任", count: 2 },
      { name: "羽山 真生", count: 2 },
      { name: "青木 博", count: 2 },
    ],
    relatedTitles: [
      { slug: "houou-isen", name: "鳳凰戦" },
      { slug: "judan-isen", name: "十段戦" },
    ],
  },
  {
    slug: "jakuou-isen",
    href: "/titles/jakuou-isen",
    code: "04 · JAKU-Ō",
    name: "雀王戦",
    shortName: "雀王",
    en: "The Jaku-Ō Championship",
    glyph: "雀",
    color: "#2563eb",
    org: "NPM",
    orgLabel: "日本プロ麻雀協会",
    orgHref: "/organizations/npm",
    holder: { name: "西村 雄一郎", note: "現雀王" },
    season: "年間リーグ戦",
    tags: ["NPM最高峰", "リーグ戦", "協会公式ルール"],
    founded: 2001,
    formatLabel: "協会リーグ戦 + 雀王決定戦",
    about: [
      "雀王戦は日本プロ麻雀協会の最高峰タイトル。リーグ戦に参加する協会員の目標となる年間タイトル戦。",
      "上位リーグほど昇級・残留が難しく、長い期間をかけて挑戦権を得る構造になっている。",
      "採用ルールは日本プロ麻雀協会公式ルール。一発・裏ドラ・カンドラあり、順位点は50-10方式。",
    ],
    rules: NPM_RULES,
    leagueTiers: [
      { code: "A1", title: "最高峰", desc: "雀王決定戦への挑戦権を争う", highlight: true },
      { code: "A2", title: "上位リーグ", desc: "A1昇級を争う" },
      { code: "B/C", title: "中位リーグ", desc: "昇降級で上位を目指す" },
      { code: "D/E/F", title: "下位リーグ", desc: "協会員の登竜門" },
    ],
    pastChampions: [
      { ep: "24", year: "2025", name: "西村 雄一郎", current: true },
      { ep: "23", year: "2024", name: "仲林 圭", href: "/players/nakabayashi" },
      { ep: "22", year: "2023", name: "仲林 圭", href: "/players/nakabayashi" },
      { ep: "21", year: "2022", name: "浅井 堂岐", href: "/players/asai" },
      { ep: "20", year: "2021", name: "渋川 難波", href: "/players/shibukawa" },
      { ep: "19", year: "2020", name: "矢島 亨" },
      { ep: "18", year: "2019", name: "堀 慎吾" },
      { ep: "17", year: "2018", name: "金 太賢" },
      { ep: "16", year: "2017", name: "金 太賢" },
      { ep: "15", year: "2016", name: "角谷 ヨウスケ" },
      { ep: "14", year: "2015", name: "木原 浩一" },
      { ep: "13", year: "2014", name: "鈴木 たろう", href: "/players/suzuki-t" },
      { ep: "12", year: "2013", name: "鈴木 たろう", href: "/players/suzuki-t" },
      { ep: "11", year: "2012", name: "鈴木 たろう", href: "/players/suzuki-t" },
      { ep: "10", year: "2011", name: "鈴木 達也" },
      { ep: "9", year: "2010", name: "鈴木 たろう", href: "/players/suzuki-t" },
      { ep: "8", year: "2009", name: "鈴木 達也" },
      { ep: "7", year: "2008", name: "小倉 孝" },
      { ep: "6", year: "2007", name: "鈴木 達也" },
      { ep: "5", year: "2006", name: "須田 良規" },
      { ep: "4", year: "2005", name: "鍛冶田 良一" },
      { ep: "3", year: "2004", name: "尾崎 嘉紀" },
      { ep: "2", year: "2003", name: "鈴木 達也" },
      { ep: "1", year: "2002", name: "土井 泰昭" },
    ],
    relatedTitles: [
      { slug: "jaryuui-sen", name: "雀竜位戦" },
      { slug: "nihon-open", name: "日本オープン" },
    ],
  },
  {
    slug: "jaryuui-sen",
    href: "/titles/jaryuui-sen",
    code: "05 · JARYŪ-I",
    name: "雀竜位戦",
    shortName: "雀竜位",
    en: "The Jaryū-i Championship",
    glyph: "竜",
    color: "#2563eb",
    org: "NPM",
    orgLabel: "日本プロ麻雀協会",
    orgHref: "/organizations/npm",
    holder: { name: "大川 冬馬", note: "現雀竜位" },
    season: "短期リーグ戦",
    tags: ["NPM", "短期昇級", "協会公式ルール"],
    formatLabel: "短期リーグ戦・原則雀王戦に準ずる",
    about: [
      "雀竜位戦は日本プロ麻雀協会を代表するタイトルの一つ。雀王戦と異なり、1年で最下級から決定戦まで勝ち上がれる可能性がある。",
      "公式概要では、原則として雀王戦に準じる形式で、規定半荘数の総合ポイントを競う短期リーグ戦とされている。",
      "新人プロでも短期間で大きなタイトルに挑める、夢のあるタイトル戦として位置付けられている。",
    ],
    rules: [...NPM_RULES, { label: "形式", value: "原則雀王戦に準ずる短期リーグ" }],
    pastChampions: [
      { ep: "24", year: "2025", name: "大川 冬馬", current: true },
      { ep: "23", year: "2024", name: "安藤 弘樹" },
      { ep: "22", year: "2023", name: "真田 槐" },
      { ep: "21", year: "2022", name: "安藤 弘樹" },
      { ep: "20", year: "2021", name: "吉田 知弘" },
      { ep: "19", year: "2020", name: "富永 修" },
      { ep: "18", year: "2019", name: "大浜 岳" },
      { ep: "17", year: "2018", name: "矢島 亨" },
      { ep: "16", year: "2017", name: "江崎 文郎" },
      { ep: "15", year: "2016", name: "江崎 文郎" },
      { ep: "14", year: "2015", name: "吉田 基成" },
      { ep: "13", year: "2014", name: "武中 進" },
      { ep: "12", year: "2013", name: "斎藤 俊" },
      { ep: "11", year: "2012", name: "渋川 難波", href: "/players/shibukawa" },
      { ep: "10", year: "2011", name: "仲林 圭", href: "/players/nakabayashi" },
      { ep: "9", year: "2010", name: "内海 元" },
      { ep: "8", year: "2009", name: "伊達 直樹" },
      { ep: "7", year: "2008", name: "福田 聡" },
      { ep: "6", year: "2007", name: "吉田 基成" },
      { ep: "5", year: "2006", name: "石野 豊" },
      { ep: "4", year: "2005", name: "小倉 孝" },
      { ep: "3", year: "2004", name: "小倉 孝" },
      { ep: "2", year: "2003", name: "鍛冶田 良一" },
      { ep: "1", year: "2002", name: "鍛冶田 良一" },
    ],
    relatedTitles: [
      { slug: "jakuou-isen", name: "雀王戦" },
      { slug: "nihon-open", name: "日本オープン" },
    ],
  },
  {
    slug: "nihon-open",
    href: "/titles/nihon-open",
    code: "06 · OPEN",
    name: "日本オープン",
    shortName: "日本OP",
    en: "The Japan Open",
    glyph: "開",
    color: "#2563eb",
    org: "NPM",
    orgLabel: "日本プロ麻雀協会",
    orgHref: "/organizations/npm",
    holder: { name: "岩崎 啓悟", note: "第22回" },
    season: "年1回 · プロアマ混合オープン",
    tags: ["NPM", "オープン", "プロアマ混合"],
    formatLabel: "一般予選・プロ予選 → 本戦 → 準決勝 → 決勝",
    about: [
      "日本オープンは、日本プロ麻雀協会が主催するプロ・アマ混合のオープンタイトル戦。",
      "一般予選・プロ予選から本戦へ進み、本戦2日目、準決勝を経て決勝5半荘で日本オープンを争う。",
      "公式ページでは、リアル対局1000人以上・ネット予選2500人規模の参加者から勝ち上がる大会として紹介されている。",
    ],
    rules: [
      { label: "採用ルール", value: "日本オープン公式ルール" },
      { label: "一発・裏ドラ", value: "あり" },
      { label: "順位点・オカ", value: "順位ウマ10-30・オカあり" },
      { label: "本戦", value: "本戦1日目 → 本戦2日目" },
      { label: "準決勝", value: "勝ち上がり + 前年度覇者の16名による総当たり戦" },
      { label: "決勝", value: "5半荘" },
    ],
    pastChampions: [
      { ep: "22", year: "2025", name: "岩崎 啓悟", current: true },
      { ep: "21", year: "2024", name: "岩崎 啓悟" },
      { ep: "20", year: "2023", name: "飯田 雅貴" },
      { ep: "19", year: "2022", name: "飯田 雅貴" },
      { ep: "18", year: "2021", name: "皆川 直毅" },
      { ep: "17", year: "2020", name: "下出 和洋" },
      { ep: "16", year: "2019", name: "魚谷 侑未" },
      { ep: "15", year: "2018", name: "渋川 難波", href: "/players/shibukawa" },
      { ep: "14", year: "2017", name: "山口 大和" },
      { ep: "13", year: "2016", name: "矢島 亨" },
      { ep: "12", year: "2015", name: "坂巻 稔永" },
      { ep: "11", year: "2014", name: "北島 路久" },
      { ep: "10", year: "2013", name: "武中 真" },
      { ep: "9", year: "2012", name: "多井 隆晴", href: "/players/taii" },
      { ep: "8", year: "2011", name: "村上 淳" },
      { ep: "7", year: "2010", name: "山下 健治" },
      { ep: "6", year: "2009", name: "藤崎 智" },
      { ep: "5", year: "2008", name: "藤崎 智" },
      { ep: "4", year: "2007", name: "中村 光一" },
      { ep: "3", year: "2006", name: "藤崎 智" },
      { ep: "2", year: "2005", name: "阿部 孝則" },
      { ep: "1", year: "2004", name: "多井 隆晴", href: "/players/taii" },
    ],
    crownRanking: [
      { name: "藤崎 智", count: 3 },
      { name: "多井 隆晴", href: "/players/taii", count: 2 },
      { name: "飯田 雅貴", count: 2 },
      { name: "岩崎 啓悟", count: 2 },
      { name: "阿部 孝則", count: 1 },
    ],
    relatedTitles: [
      { slug: "jakuou-isen", name: "雀王戦" },
      { slug: "jaryuui-sen", name: "雀竜位戦" },
    ],
  },
  {
    slug: "saikouisen",
    href: "/titles/saikouisen",
    code: "07 · SAIKŌI",
    name: "最高位戦",
    shortName: "最高位",
    en: "The Saikōi Championship",
    glyph: "最",
    color: "#7c3aed",
    org: "SAIKOUISEN",
    orgLabel: "最高位戦日本プロ麻雀協会",
    orgHref: "/organizations/saikouisen",
    holder: { name: "牧野 伸彦", note: "第50期 (2025)" },
    season: "年間リーグ戦",
    tags: ["最高位戦最高峰", "リーグ戦", "最高位戦ルール"],
    founded: 1976,
    formatLabel: "A1を頂点とするリーグ戦 + 最高位決定戦",
    about: [
      "最高位戦は最高位戦日本プロ麻雀協会の最高峰タイトル。団体創設以来続く、プロ麻雀を代表する長期リーグ戦。",
      "最高位戦ルールは30,000点持ち30,000点返し・オカなし・ウマ10-30。一発、裏ドラ、槓ドラ、槓裏がある。",
      "リーグ戦を勝ち抜いた上位者が最高位決定戦で年間王者を争う。",
    ],
    rules: SAIKOUISEN_RULES,
    leagueTiers: [
      { code: "A1", title: "最高峰", desc: "最高位決定戦を争う", highlight: true },
      { code: "A2", title: "上位リーグ", desc: "A1昇級を目指す" },
      { code: "B/C/D", title: "昇降級リーグ", desc: "段階的に上位を目指す" },
    ],
    pastChampions: [
      { ep: "50", year: "2025", name: "牧野 伸彦", current: true },
      { ep: "49", year: "2024", name: "石井 一馬" },
      { ep: "48", year: "2023", name: "竹内 元太" },
      { ep: "47", year: "2022", name: "竹内 元太" },
      { ep: "46", year: "2021", name: "鈴木 優" },
      { ep: "45", year: "2020", name: "醍醐 大" },
      { ep: "44", year: "2019", name: "坂本 大志" },
      { ep: "43", year: "2018", name: "近藤 誠一" },
      { ep: "42", year: "2017", name: "村上 淳" },
      { ep: "41", year: "2016", name: "近藤 誠一" },
      { ep: "40", year: "2015", name: "近藤 誠一" },
      { ep: "39", year: "2014", name: "村上 淳" },
      { ep: "38", year: "2013", name: "新井 啓文" },
      { ep: "37", year: "2012", name: "近藤 誠一" },
      { ep: "36", year: "2011", name: "石橋 伸洋" },
      { ep: "35", year: "2010", name: "村上 淳" },
      { ep: "34", year: "2009", name: "飯田 正人" },
      { ep: "33", year: "2008", name: "飯田 正人" },
      { ep: "32", year: "2007", name: "張 敏賢" },
      { ep: "31", year: "2006", name: "張 敏賢" },
      { ep: "30", year: "2005", name: "古久根 英孝" },
      { ep: "29", year: "2004", name: "尾崎 公太" },
      { ep: "28", year: "2003", name: "飯田 正人" },
      { ep: "27", year: "2002", name: "古久根 英孝" },
      { ep: "26", year: "2001", name: "古久根 英孝" },
      { ep: "25", year: "2000", name: "飯田 正人" },
      { ep: "24", year: "1999", name: "金子 正輝" },
      { ep: "23", year: "1998", name: "飯田 正人" },
      { ep: "22", year: "1997", name: "岩川 聖基" },
      { ep: "21", year: "1996", name: "五十嵐 毅" },
      { ep: "20", year: "1995", name: "飯田 正人" },
      { ep: "19", year: "1994", name: "井出 洋介" },
      { ep: "18", year: "1993", name: "徳久 英人" },
      { ep: "17", year: "1992", name: "飯田 正人" },
      { ep: "16", year: "1991", name: "飯田 正人" },
      { ep: "15", year: "1990", name: "飯田 正人" },
      { ep: "14", year: "1989", name: "飯田 正人" },
      { ep: "13", year: "1988", name: "西田 秀幾" },
      { ep: "12", year: "1987", name: "金子 正輝" },
      { ep: "11", year: "1986", name: "金子 正輝" },
      { ep: "10", year: "1985", name: "佐藤 孝平" },
      { ep: "9", year: "1984", name: "金子 正輝" },
      { ep: "8", year: "1983", name: "青野 滋" },
      { ep: "7", year: "1982", name: "大隈 秀夫" },
      { ep: "6", year: "1981", name: "狩野 洋一" },
      { ep: "5", year: "1980", name: "田村 光昭" },
      { ep: "4", year: "1979", name: "小島 武夫" },
      { ep: "3", year: "1978", name: "小島 武夫" },
      { ep: "2", year: "1977", name: "田村 光昭" },
      { ep: "1", year: "1976", name: "灘 麻太郎・川田 隆" },
    ],
    crownRanking: [
      { name: "飯田 正人", count: 10 },
      { name: "近藤 誠一", count: 4 },
      { name: "金子 正輝", count: 4 },
      { name: "古久根 英孝", count: 3 },
      { name: "村上 淳", count: 3 },
    ],
    relatedTitles: [
      { slug: "saikouisen-classic", name: "最高位戦Classic" },
      { slug: "ryuou-sen", name: "發王戦" },
    ],
  },
  {
    slug: "saikouisen-classic",
    href: "/titles/saikouisen-classic",
    code: "08 · CLASSIC",
    name: "飯田正人杯 最高位戦Classic",
    shortName: "Classic",
    en: "The Saikōisen Classic",
    glyph: "典",
    color: "#7c3aed",
    org: "SAIKOUISEN",
    orgLabel: "最高位戦日本プロ麻雀協会",
    orgHref: "/organizations/saikouisen",
    holder: { name: "小池 諒", note: "現Classic" },
    season: "Classicルール採用タイトル",
    tags: ["最高位戦", "Classic", "一発なし"],
    formatLabel: "最高位戦Classicルールによるタイトル戦",
    about: [
      "最高位戦Classicは、現行の最高位戦ルールとは異なるClassicルールで行われるタイトル戦。",
      "Classicルールでは、一発・裏ドラがなく、順位点は12-4方式。ノーテン罰符なし、連荘は親のアガリのみなど、現行ルールと大きく異なる。",
      "『飯田正人杯』として、最高位戦内でもルール思想の違いがはっきり出るタイトル戦になっている。",
    ],
    rules: SAIKOUISEN_CLASSIC_RULES,
    pastChampions: [
      { ep: "19", year: "2025", name: "小池 諒", current: true },
      { ep: "18", year: "2024", name: "石井 一馬" },
      { ep: "17", year: "2023", name: "伊藤 高志" },
      { ep: "16", year: "2022", name: "下出 和洋" },
      { ep: "15", year: "2021", name: "平島 晶太" },
      { ep: "14", year: "2019", name: "森本 俊介" },
      { ep: "13", year: "2018", name: "長谷川 来輝" },
      { ep: "12", year: "2017", name: "堀 慎吾" },
      { ep: "11", year: "2016", name: "飯沼 雅由" },
      { ep: "10", year: "2015", name: "石井 一馬" },
      { ep: "9", year: "2014", name: "村上 淳" },
      { ep: "8", year: "2013", name: "木原 浩一" },
      { ep: "7", year: "2012", name: "松ヶ瀬 隆弥" },
      { ep: "6", year: "2011", name: "宇野 公介" },
      { ep: "5", year: "2010", name: "村上 淳" },
      { ep: "4", year: "2009", name: "坂本 大志" },
      { ep: "3", year: "2008", name: "下出 和洋" },
      { ep: "2", year: "2007", name: "飯田 正人" },
      { ep: "1", year: "2006", name: "立川 宏" },
    ],
    crownRanking: [
      { name: "石井 一馬", href: "/players/ishii", count: 2 },
      { name: "下出 和洋", count: 2 },
      { name: "村上 淳", count: 2 },
    ],
    relatedTitles: [
      { slug: "saikouisen", name: "最高位戦" },
      { slug: "ryuou-sen", name: "發王戦" },
    ],
  },
  {
    slug: "ryuou-sen",
    href: "/titles/ryuou-sen",
    code: "09 · RYŪŌ",
    name: "發王戦",
    shortName: "發王",
    en: "The Ryūō Championship",
    glyph: "發",
    color: "#7c3aed",
    org: "SAIKOUISEN",
    orgLabel: "最高位戦日本プロ麻雀協会",
    orgHref: "/organizations/saikouisen",
    holder: { name: "宮﨑 和樹", note: "現發王" },
    season: "オープントーナメント",
    tags: ["最高位戦", "オープン", "トーナメント"],
    founded: 1992,
    formatLabel: "最高位戦ルール・トーナメント方式",
    about: [
      "發王戦は最高位戦日本プロ麻雀協会主催のタイトル戦。1992年創設で、一般参加も可能なオープン戦。",
      "本戦以降は、同じ面子で半荘2〜3回を打ち、上位2名が勝ち上がるトーナメント方式を採用する。",
      "採用ルールは最高位戦ルール。条件戦の醍醐味が強く出るタイトル戦として位置付けられている。",
    ],
    rules: [...SAIKOUISEN_RULES, { label: "形式", value: "同卓者内の上位2名勝ち上がり" }],
    pastChampions: [
      { ep: "33", year: "2025", name: "宮﨑 和樹", current: true },
      { ep: "32", year: "2024", name: "寿" },
      { ep: "31", year: "2023", name: "有賀 一宏" },
      { ep: "30", year: "2022", name: "仲林 圭" },
      { ep: "29", year: "2021", name: "仲林 圭" },
      { ep: "28", year: "2019", name: "白鳥 翔" },
      { ep: "27", year: "2018", name: "中嶋 和正" },
      { ep: "26", year: "2017", name: "石野 豊" },
      { ep: "25", year: "2016", name: "松本 吉弘" },
      { ep: "24", year: "2015", name: "中嶋 和正" },
      { ep: "23", year: "2014", name: "水巻 渉" },
      { ep: "22", year: "2013", name: "水巻 渉" },
      { ep: "21", year: "2012", name: "佐藤 聖誠" },
      { ep: "20", year: "2011", name: "佐藤 聖誠" },
      { ep: "19", year: "2010", name: "石橋 伸洋" },
      { ep: "18", year: "2009", name: "土井 泰昭" },
      { ep: "17", year: "2008", name: "水巻 渉" },
      { ep: "16", year: "2007", name: "石野 豊" },
      { ep: "15", year: "2006", name: "竹内 孝之" },
      { ep: "14", year: "2005", name: "瀬戸熊 直樹" },
      { ep: "13", year: "2004", name: "藤中 慎一郎" },
      { ep: "12", year: "2003", name: "菊池 俊幸" },
      { ep: "11", year: "2002", name: "菊池 俊幸" },
      { ep: "10", year: "2001", name: "吉田 幸雄" },
      { ep: "9", year: "2000", name: "佐々木 慶太" },
      { ep: "8", year: "1999", name: "土井 泰昭" },
      { ep: "7", year: "1998", name: "伊藤 優孝" },
      { ep: "6", year: "1997", name: "伊藤 優孝" },
      { ep: "5", year: "1996", name: "原 浩明" },
      { ep: "4", year: "1995", name: "原 浩明" },
      { ep: "3", year: "1994", name: "伊東 一" },
      { ep: "2", year: "1993", name: "新津 潔" },
      { ep: "1", year: "1992", name: "田中 英知" },
    ],
    crownRanking: [
      { name: "水巻 渉", count: 3 },
      { name: "原 浩明", count: 2 },
      { name: "伊藤 優孝", count: 2 },
      { name: "土井 泰昭", count: 2 },
      { name: "菊池 俊幸", count: 2 },
    ],
    relatedTitles: [
      { slug: "saikouisen", name: "最高位戦" },
      { slug: "saikouisen-classic", name: "最高位戦Classic" },
    ],
  },
  {
    slug: "reishouisen",
    href: "/titles/reishouisen",
    code: "10 · REISHŌ",
    name: "令昭位戦",
    shortName: "令昭位",
    en: "The Reishōi Championship",
    glyph: "令",
    color: "var(--gold)",
    org: "RMU",
    orgLabel: "Real Mahjong Unit",
    orgHref: "/organizations/rmu",
    holder: { name: "小川 光", note: "第17期 (2026)" },
    season: "A1・A2・B1は年間、B2以下は半期制",
    tags: ["RMU最高峰", "リーグ戦", "Aルール"],
    founded: 2009,
    formatLabel: "アスリートコース所属選手による階層リーグ",
    about: [
      "令昭位戦はRMUのアスリートコース所属選手のみで行われる最高峰リーグ戦。A1優勝者を令昭位と称する。",
      "公式概要では、A1・A2・B1は年間1期、B2以下は1期5節・半荘20回戦で年2期開催とされている。",
      "RMU公式Aルールを基準に、年間リーグと決定戦で総合力を競う。",
    ],
    rules: RMU_A_RULES,
    leagueTiers: [
      { code: "A1", title: "最高峰", desc: "優勝者を令昭位と称する", highlight: true },
      { code: "A2/B1", title: "年間リーグ", desc: "A1昇級・残留を争う" },
      { code: "B2以下", title: "半期リーグ", desc: "5節20回戦で昇降級" },
    ],
    pastChampions: [
      { ep: "17", year: "2025", name: "小川光", current: true },
      { ep: "16", year: "2024", name: "河野高志" },
      { ep: "15", year: "2023", name: "谷井茂文" },
      { ep: "14", year: "2022", name: "楢原和人" },
      { ep: "13", year: "2021", name: "河野高志" },
      { ep: "12", year: "2020", name: "河野高志" },
      { ep: "11", year: "2019", name: "多井隆晴" },
      { ep: "10", year: "2018", name: "谷井茂文" },
      { ep: "9", year: "2017", name: "松ヶ瀬隆弥 最高位戦日本麻雀協会 鈴木聡一郎による観戦記-->" },
      { ep: "8", year: "2016", name: "多井隆晴" },
      { ep: "7", year: "2015", name: "阿部孝則" },
      { ep: "6", year: "2014", name: "多井隆晴" },
      { ep: "5", year: "2013", name: "河野高志" },
      { ep: "4", year: "2012", name: "谷井茂文" },
      { ep: "3", year: "2011", name: "多井隆晴" },
      { ep: "2", year: "2010", name: "阿部孝則" },
      { ep: "1", year: "2009", name: "多井隆晴" },
    ],
    crownRanking: [
      { name: "多井 隆晴", href: "/players/taii", count: 5 },
      { name: "河野 高志", count: 4 },
      { name: "谷井 茂文", count: 3 },
      { name: "阿部 孝則", count: 2 },
      { name: "松ヶ瀬 隆弥", count: 1 },
    ],
    relatedTitles: [
      { slug: "rmu-crown", name: "RMUクラウン" },
      { slug: "tiara-league", name: "ティアラリーグ" },
    ],
  },
  {
    slug: "rmu-crown",
    href: "/titles/rmu-crown",
    code: "11 · CROWN",
    name: "RMUクラウン",
    shortName: "クラウン",
    en: "The RMU Crown",
    glyph: "冠",
    color: "var(--gold)",
    org: "RMU",
    orgLabel: "Real Mahjong Unit",
    orgHref: "/organizations/rmu",
    holder: { name: "福原 慎平", note: "第17期" },
    season: "年1回 · オープンタイトル",
    tags: ["RMU", "G1", "オープン"],
    formatLabel: "会員・一般参加可能なG1オープンタイトル",
    about: [
      "RMUクラウンは、RMUにおいて最も価値のあるG1タイトルとして位置付けられるオープンタイトル戦。",
      "年1回開催され、RMU会員・一般を問わず参加可能。本戦にはRMUライセンスプロや友好団体所属選手がシードされる。",
      "予選・本戦を勝ち抜き、準決勝・決勝でクラウンを争う。",
    ],
    rules: [...RMU_A_RULES, { label: "参加", value: "会員・一般参加可能" }],
    pastChampions: [
      { ep: "17", year: "2025", name: "福原慎平", current: true },
      { ep: "16", year: "2024", name: "河野高志" },
      { ep: "15", year: "2023", name: "下石戟" },
      { ep: "14", year: "2022", name: "浅井裕介" },
      { ep: "13", year: "2021", name: "浅井裕介" },
      { ep: "12", year: "2020", name: "朝倉ゆかり" },
      { ep: "11", year: "2019", name: "齋藤豪" },
      { ep: "10", year: "2018", name: "伊澤興" },
      { ep: "9", year: "2017", name: "河野高志" },
      { ep: "8", year: "2016", name: "河野高志" },
      { ep: "7", year: "2015", name: "岡澤和洋" },
      { ep: "6", year: "2014", name: "川上貴史" },
      { ep: "5", year: "2013", name: "多井隆晴" },
      { ep: "4", year: "2012", name: "平山友厚" },
      { ep: "3", year: "2011", name: "古久根英孝" },
      { ep: "2", year: "2010", name: "渡辺卓也" },
      { ep: "1", year: "2009", name: "山谷克也" },
    ],
    crownRanking: [
      { name: "河野 高志", count: 3 },
      { name: "浅井 裕介", count: 2 },
      { name: "福原 慎平", count: 1 },
      { name: "下石 戟", href: "/players/shimoishi", count: 1 },
      { name: "齋藤 豪", count: 1 },
    ],
    relatedTitles: [
      { slug: "reishouisen", name: "令昭位戦" },
      { slug: "tiara-league", name: "ティアラリーグ" },
    ],
  },
  {
    slug: "tiara-league",
    href: "/titles/tiara-league",
    code: "12 · TIARA",
    name: "ティアラリーグ",
    shortName: "ティアラ",
    en: "The Tiara League",
    glyph: "姫",
    color: "var(--gold)",
    org: "RMU",
    orgLabel: "Real Mahjong Unit",
    orgHref: "/organizations/rmu",
    holder: { name: "角 葉子", note: "第11期 (2025)" },
    season: "女流アスリートリーグ",
    tags: ["RMU", "女流", "リーグ戦"],
    founded: 2015,
    formatLabel: "女流アスリート選手による5節リーグ",
    about: [
      "ティアラリーグはRMUの女流アスリート選手によるリーグ戦。2015年に新設された。",
      "5節のリーグ戦で、女流令昭位決定戦出場選手、昇級者、降級者を決める。",
      "RMU公式ルール体系のもと、女流選手の年間成績を競うタイトル戦として運営される。",
    ],
    rules: RMU_B_RULES,
    leagueTiers: [
      { code: "A", title: "上位リーグ", desc: "女流令昭位決定戦を目指す", highlight: true },
      { code: "B以下", title: "昇降級", desc: "5節で昇級・降級を争う" },
    ],
    pastChampions: [
      { ep: "11", year: "2025", name: "角葉子", current: true },
      { ep: "10", year: "2024", name: "金宮じゅん" },
      { ep: "9", year: "2023", name: "里中花奈" },
      { ep: "8", year: "2022", name: "千本松紘子" },
      { ep: "7", year: "2021", name: "汐宮あまね" },
      { ep: "6", year: "2020", name: "新倉美紀" },
      { ep: "5", year: "2019", name: "白田みお" },
      { ep: "4", year: "2018", name: "里中花奈" },
      { ep: "3", year: "2017", name: "京杜なお" },
      { ep: "2", year: "2016", name: "南地祐圭" },
      { ep: "1", year: "2015", name: "白田みお" },
    ],
    relatedTitles: [
      { slug: "reishouisen", name: "令昭位戦" },
      { slug: "rmu-crown", name: "RMUクラウン" },
    ],
  },
  {
    slug: "shouou-isen",
    href: "/titles/shouou-isen",
    code: "13 · SHŌŌ",
    name: "将王戦",
    shortName: "将王",
    en: "The Shōō Championship",
    glyph: "将",
    color: "#2f5c3f",
    org: "MU",
    orgLabel: "麻将連合",
    orgHref: "/organizations/mu",
    holder: { name: "石原 真人", note: "第23期" },
    season: "μリーグ + 将王決定戦",
    tags: ["μ最高峰", "リーグ戦", "μリーグルール"],
    formatLabel: "期首順位上位10名のμリーグ + 将王決定戦",
    about: [
      "将王は麻将連合の最高峰タイトル。公式ページでは『将王』をμ最高峰タイトルの称号としている。",
      "将王を除いた期首順位上位10名のプロが10節40半荘を行い、上位3名が将王決定戦で現将王への挑戦権を得る。",
      "μリーグルールではテンパイ料なし。順位点は12-4方式で、素点と順位点の合計を競う。",
    ],
    rules: MU_LEAGUE_RULES,
    pastChampions: [
      { ep: "23", year: "2025", name: "石原 真人", current: true },
      { ep: "22", year: "2024", name: "忍田 幸夫" },
      { ep: "21", year: "2023", name: "むく 大樹" },
      { ep: "20", year: "2022", name: "忍田 幸夫" },
      { ep: "19", year: "2021", name: "小林 剛", href: "/players/kobayashi" },
      { ep: "18", year: "2020", name: "木村 和幸" },
      { ep: "17", year: "2019", name: "原 浩明" },
      { ep: "16", year: "2018", name: "武則 輝海" },
      { ep: "15", year: "2017", name: "井出 洋介" },
      { ep: "14", year: "2016", name: "忍田 幸夫" },
      { ep: "13", year: "2015", name: "忍田 幸夫" },
      { ep: "12", year: "2014", name: "清水 英二" },
      { ep: "11", year: "2013", name: "忍田 幸夫" },
      { ep: "10", year: "2012", name: "忍田 幸夫" },
      { ep: "9", year: "2011", name: "小林 剛", href: "/players/kobayashi" },
      { ep: "8", year: "2010", name: "武則 輝海" },
      { ep: "7", year: "2009", name: "小林 剛", href: "/players/kobayashi" },
      { ep: "6", year: "2008", name: "柏原 純" },
      { ep: "5", year: "2007", name: "三原 孝博" },
      { ep: "4", year: "2006", name: "三原 孝博" },
      { ep: "3", year: "2005", name: "小林 剛", href: "/players/kobayashi" },
      { ep: "2", year: "2004", name: "原 浩明" },
      { ep: "1", year: "2003", name: "原 浩明" },
    ],
    crownRanking: [
      { name: "忍田 幸夫", count: 6 },
      { name: "小林 剛", href: "/players/kobayashi", count: 4 },
      { name: "原 浩明", count: 3 },
      { name: "三原 孝博", count: 2 },
      { name: "武則 輝海", count: 2 },
    ],
    relatedTitles: [
      { slug: "big1-cup", name: "BIG1カップ" },
      { slug: "mu-m1-cup", name: "μ-M1カップ" },
    ],
  },
  {
    slug: "big1-cup",
    href: "/titles/big1-cup",
    code: "14 · BIG1",
    name: "BIG1カップ",
    shortName: "BIG1",
    en: "The BIG1 Cup",
    glyph: "一",
    color: "#2f5c3f",
    org: "MU",
    orgLabel: "麻将連合",
    orgHref: "/organizations/mu",
    holder: { name: "鹿 健太郎", note: "第29回" },
    season: "年1回 · オープン予選あり",
    tags: ["μ", "オープン", "μカップルール"],
    formatLabel: "固定卓トーナメント + プロアマ予選",
    about: [
      "BIG1カップは、麻将連合の中で最も長い歴史を持つタイトル戦。",
      "固定メンツの同卓者で3回戦を行い、上位2名が勝ち抜けるトーナメント戦を主に採用している。",
      "プロアマ予選はμカップルールでの半荘5回戦。4回戦終了時にマイナスの選手は敗退し、上位20％が全国大会参加資格を得る。",
    ],
    rules: [...MU_CUP_RULES, { label: "予選", value: "半荘5回戦・4回戦終了時マイナス敗退" }],
    pastChampions: [
      { ep: "29", year: "2026", name: "鹿 健太郎", current: true },
      { ep: "28", year: "2025", name: "地野 彰信" },
      { ep: "27", year: "2024", name: "地主 琢磨" },
      { ep: "26", year: "2023", name: "大塚 翼" },
      { ep: "25", year: "2022", name: "竹内 元太" },
      { ep: "24", year: "2021", name: "山崎 淑弥" },
      { ep: "23", year: "2020", name: "醍醐 大" },
      { ep: "22", year: "2019", name: "加藤 博士" },
      { ep: "21", year: "2018", name: "板川 和俊" },
      { ep: "20", year: "2017", name: "奈良 圭純" },
      { ep: "19", year: "2016", name: "忍田 幸夫" },
      { ep: "18", year: "2015", name: "楠橋 思" },
      { ep: "17", year: "2014", name: "寺本 喜一" },
      { ep: "16", year: "2013", name: "松井 一義" },
      { ep: "15", year: "2012", name: "松井 一義" },
      { ep: "14", year: "2011", name: "山舗 徹" },
      { ep: "13", year: "2010", name: "楠橋 思" },
      { ep: "12", year: "2009", name: "井出 洋介" },
      { ep: "11", year: "2008", name: "忍田 幸夫" },
      { ep: "10", year: "2007", name: "鈴木たろう" },
      { ep: "9", year: "2006", name: "黒澤耕一郎" },
      { ep: "8", year: "2005", name: "吉田 賞二" },
      { ep: "7", year: "2004", name: "山本 裕司" },
      { ep: "6", year: "2003", name: "松井 一義" },
      { ep: "5", year: "2002", name: "松井 一義" },
      { ep: "4", year: "2001", name: "井出 洋介" },
      { ep: "3", year: "2000", name: "西田 秀幾" },
      { ep: "2", year: "1999", name: "井出 洋介" },
      { ep: "1", year: "1998", name: "原 浩明" },
    ],
    crownRanking: [
      { name: "松井 一義", count: 4 },
      { name: "井出 洋介", count: 3 },
      { name: "忍田 幸夫", count: 2 },
      { name: "楠橋 思", count: 2 },
      { name: "原 浩明", count: 1 },
    ],
    relatedTitles: [
      { slug: "shouou-isen", name: "将王戦" },
      { slug: "mu-m1-cup", name: "μ-M1カップ" },
    ],
  },
  {
    slug: "mu-m1-cup",
    href: "/titles/mu-m1-cup",
    code: "15 · μ-M1",
    name: "μ-M1カップ",
    shortName: "μ-M1",
    en: "The μ-M1 Cup",
    glyph: "μ",
    color: "#2f5c3f",
    org: "MU",
    orgLabel: "麻将連合",
    orgHref: "/organizations/mu",
    holder: { name: "地主 琢磨", note: "第24回" },
    season: "7月〜翌5月 月例予選 · 6月本戦",
    tags: ["μ", "月例予選", "μカップルール"],
    formatLabel: "月例予選 → 1次・2次戦 → 決勝大会",
    about: [
      "μ-M1カップは年間にわたって予選を開催する麻将連合のタイトル戦。",
      "毎年7月から翌年5月まで毎月第3日曜に月例予選を行い、6月に1次・2次戦と決勝大会を行う。",
      "月例予選は半荘4回＋1回戦。上位20％に本戦参加権利が与えられる。",
    ],
    rules: [...MU_CUP_RULES, { label: "月例予選", value: "半荘4回 + 1回戦" }],
    pastChampions: [
      { ep: "24", year: "2026", name: "地主 琢磨", current: true },
      { ep: "23", year: "2025", name: "中西 龍" },
      { ep: "22", year: "2024", name: "明村 諭" },
      { ep: "21", year: "2023", name: "野村 祐三" },
      { ep: "20", year: "2022", name: "三原 孝博" },
      { ep: "19", year: "2021", name: "山部 正人" },
      { ep: "18", year: "2020", name: "熊谷 聡一" },
      { ep: "17", year: "2019", name: "岡田 桂" },
      { ep: "16", year: "2018", name: "並川 貞行" },
      { ep: "15", year: "2017", name: "地野 彰信" },
      { ep: "14", year: "2016", name: "斉田 喜一" },
      { ep: "13", year: "2015", name: "忍田 幸夫" },
      { ep: "12", year: "2014", name: "松井 一義" },
      { ep: "11", year: "2013", name: "高見沢治幸" },
      { ep: "10", year: "2012", name: "三原 孝博" },
      { ep: "9", year: "2011", name: "梶井 薫" },
      { ep: "8", year: "2010", name: "須藤 泰久" },
      { ep: "7", year: "2009", name: "須藤 泰久" },
      { ep: "6", year: "2008", name: "山本 裕司" },
      { ep: "5", year: "2007", name: "木村 和幸" },
      { ep: "4", year: "2006", name: "寺本 喜一" },
      { ep: "3", year: "2005", name: "寺本 喜一" },
      { ep: "2", year: "2004", name: "井上 忠重" },
      { ep: "1", year: "2003", name: "富宿 親" },
    ],
    crownRanking: [
      { name: "寺本 喜一", count: 2 },
      { name: "須藤 泰久", count: 2 },
      { name: "三原 孝博", count: 2 },
      { name: "地主 琢磨", count: 1 },
      { name: "中西 龍", count: 1 },
    ],
    relatedTitles: [
      { slug: "shouou-isen", name: "将王戦" },
      { slug: "big1-cup", name: "BIG1カップ" },
    ],
  },
];

export type FilterTab = {
  key: "ALL" | OrgCode;
  label: string;
  en: string;
  color: string;
};

export const TITLE_FILTERS: FilterTab[] = [
  { key: "ALL", label: "ALL", en: "全タイトル", color: "var(--ink)" },
  { key: "JPML", label: "JPML", en: "連盟", color: "var(--vermilion)" },
  { key: "NPM", label: "NPM", en: "協会", color: "#2563eb" },
  { key: "SAIKOUISEN", label: "最高位戦", en: "Saikōisen", color: "#7c3aed" },
  { key: "RMU", label: "RMU", en: "Real Mahjong Unit", color: "var(--gold)" },
  { key: "MU", label: "μ", en: "麻将連合", color: "#2f5c3f" },
];

export function getTitleBySlug(slug: string): TitleData | undefined {
  return TITLES.find((t) => t.slug === slug);
}
